### ISSUE TITLE
Freezer menu garbles charset or locks up some software / reproducable

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-core#102]
[COMMERC.zip](https://github.com/MEGA65/mega65-core/files/3632957/COMMERC.zip)
Nebulus tower gets messed up visibily after entering / leaving freeze menu. Rags to riches also is buggy or cant be freezed at all. Both attached in d81.

**Comment by rdpeake** [comment]
No errors seem to show up running these on the current bitstream
