### ISSUE TITLE
GEOS preview destroys freeze menu (reproducable)

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-core#103]
GEOS preview destroys freeze menu. Disk image attached.
[GEOSM65.zip](https://github.com/MEGA65/mega65-core/files/3632958/GEOSM65.zip)

**Comment by rdpeake** [comment]
Also present on the geos shipped with the dev kit as well as this preview image

**Comment by lydon42** [comment]
This can't be reproduced with current release-prep disk and development head.
