### ISSUE TITLE
CIA TOD seems to be too slow

### ISSUE THREAD

**Issue by lgblgblgb** [MEGA65/mega65-core#106]
Still with CIA stuff, I measured 20sec of TOD second counting on the screen as about 29sec of real time with the stop watch app of my smart phone :) So it seems M65 TOD update is about 50% slower than it should be? But also NTSC/PAL stuff can effect this maybe (I am not sure) bit not as much as here I noticed, probably. Interestingly the timer value looks like in pair what VICE/x64 shows just the TOD looks slower.

Interestingly even on VICE 30 sec real of "TOD time" is 36 sec real time, though I tried with PAL/NTSC, sounds interesting (real CIA - AFAIK - would maintain TOD clock from the 50/60Hz sampled from the power supply 9V AC, IIRC so it depends on the region of frequency of the mains ...). But with M65 the difference looks bigger anyway.

The TOD second value can be seen with my test program mentioned and included in issue #104

**Comment by gardners** [comment]
Confirmed that problem is real.

**Comment by gardners** [comment]
Above commit patches i2cstatus.c to also show CIA TOD with RTC, so that we can very easily compare speeds.

Ideally we should switch between 50Hz and 60Hz clock, based on PAL vs NTSC.

**Comment by gardners** [comment]
Above commits should fix the remaining known discrepencies.

**Comment by frehwagen** [comment]
Fixed and successfully tested together with #163, merged back to stable_base so this is going to close now.
