### ISSUE TITLE
Floppies seem to get erased when used in real drive

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#110]
Anton reports that after having a disk in M65, it seems to get erased.

**Comment by adtbm** [comment]
The erase only happens, when "write-protect"is not enabled on the disc.
The erase happens, as soon as you try to acces the disc, i.e. LOAD"$",8

**Comment by gardners** [comment]
Deft I believe confirmed this fixed in the unstable branch on the 12NOV19 test session.
Confirm, merge and close as appropriate.

**Comment by gardners** [comment]
@frehwagen I think this one is ready for collapsing onto stable_base

**Comment by bluewaysw** [comment]
It is part of stable_base since the early beginning and has been tested by Deft in this context.
