### ISSUE TITLE
MEGA65 doesn't leave bootup without a disc inserted

### ISSUE THREAD

**Issue by adtbm** [MEGA65/mega65-core#111]
When you set the MEGA65 in "BIOS" to use the internal 3.5 drive and you don't have a disc inserted, MEGA65 will not finish bootup, it's searching for a disc and the cursor never shows up.
Untill you either:
- insert a disc (doesn't matter if blank, corrupt or written)
- boot into c64 mode

**Comment by rdpeake** [comment]
Not present on current bit stream
