### ISSUE TITLE
Something still a bit off with the SIDs (or probably filters)

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-core#112]
Sometimes SID sounds do not properly fade out or get filtered out which causes them to hang or otherwise sound abnormal. A good example for those with wooden ears is Wizard of Wor (attached).
[Wizard_Of_Wor.zip](https://github.com/MEGA65/mega65-core/files/3799114/Wizard_Of_Wor.zip)

**Comment by lydon42** [comment]
Closed in favor of #449
