### ISSUE TITLE
Freeze menu should offer disk chooser for both drives

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#126]
Currently you can't choose a disk image for the 2nd internal drive.  This should be fixed.

**Comment by gardners** [comment]
Fixed in unstable branch + updates to freeze menu.

**Comment by bluewaysw** [comment]
This is beeing handled on the 116- branch together with issue #116 related changes.
Just decided to include 2 real floppy support to the branch as well, because it already contains a lot of fixes that relate to the dual drive support in freezer/disk chooser.

**Comment by adtbm** [comment]
reviewing #116 issue. 
i have encountered issues mounting images.
in my example i mounted an image to drive ID#0 and an Image to Drive ID#2
it resulted, that the internal 3.5 floppy drive was accessed while loading "$",9 NOT the image i've mounted

1st picture shows current mounting state after powering on:
![2019-11-25 18 03 26](https://user-images.githubusercontent.com/35996116/69562148-dfb30900-0fae-11ea-9ef3-8f48ac7a2449.jpg)

2nd picture shows image loaded for ID 0
![2019-11-25 18 03 40](https://user-images.githubusercontent.com/35996116/69562161-e5a8ea00-0fae-11ea-87dc-fdfbd5dc2c50.jpg)

3rd picture shows image loaded for ID 1
![2019-11-25 18 04 05](https://user-images.githubusercontent.com/35996116/69562170-eb063480-0fae-11ea-86d9-fd8fedeabb40.jpg)

4th picture shows mounting state after mounting images to 0 & 1 -looks ok-
![2019-11-25 18 04 14](https://user-images.githubusercontent.com/35996116/69562189-f0637f00-0fae-11ea-8f6a-0d6ca25b18f6.jpg)

5th picture shows correct mounted image after LOAD"$",8   -OK-
![2019-11-25 18 04 35](https://user-images.githubusercontent.com/35996116/69562200-f5c0c980-0fae-11ea-9a11-9d9a75c7635d.jpg)

6th picture shows INCORRECT mounted drive after LOAD"$",9   -NOT OK-
It shows the content of the 3.5 floppy disc.

so the previousely mounted image for ID 1 has not been mounted, but the 3.5 disc drive has been moved from ID0 to ID 1 and has been mounted as ID 1
![2019-11-25 18 04 52](https://user-images.githubusercontent.com/35996116/69562215-fc4f4100-0fae-11ea-89f6-23408a798cc1.jpg)

**Comment by adtbm** [comment]
This behaviour is reproduceable and happens every time

**Comment by adtbm** [comment]
UPDATE this BUG only happens when the image, you try to mount to ID0 is MEGA65.d81

**Comment by adtbm** [comment]
Pauls updated (redesigned) Freezer from today (posted in Skype 12:51), solves the problem
