### ISSUE TITLE
issue 115 nexys4ddr-widget-20191105.02-HEAD_n-13bf229+DIRTY.bit freeze menu not working

### ISSUE THREAD

**Issue by adtbm** [MEGA65/mega65-core#128]
nexys4ddr-widget-20191105.02-HEAD_n-13bf229+DIRTY.bit

Freezemenu crashes on leaving
regardless if in C65 or c64 mode

**Comment by adtbm** [comment]
same issue on stable bitstream:
nexys4ddr-widget-20191103.15-HEAD_n-4034f19+DIRTY.bit

**Comment by gardners** [comment]
This seems to be randomly fixed by #116. That this should work is totally unexplained.  It would still be good to discover the root cause.
