### ISSUE TITLE
Feature Request: crossfader for SIDs

### ISSUE THREAD

**Issue by SvOlli** [MEGA65/mega65-core#13]
I think it would be nice if each SID would not  be fixed to a "left" or "right" channel, but have an additional register (maybe $D43F, $D47F, ...) that would pinpoint the "position" of the audio like a crossfader (-128/-127 as left channel, 127 as right channel and 0 for both channels, other values interpolate).

**Comment by gardners** [comment]
Hello,

Being able to pan the SIDs across is possible, but will require a bit of
work to add cross-faders.  A simple binary left/right selection would be a
much simpler proposition. Anyway, if someone is interested in implementing
the cross-fader, and the hardware resources weren't problematic, we would
welcome the enhancement.

Paul.
