### ISSUE TITLE
4-bit glyph mode with horizontal flip doesn't flip nybl order

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#131]
Pixel pairs are not flipped, when they should be.

**Comment by gardners** [comment]
Will test this fix in the morning.

**Comment by gardners** [comment]
Confirm fixed.
@frehwagen this one is ready for you to merge into 114 or wherever you think best.

**Comment by lydon42** [comment]
Tested with Shallan's Perseus with recent pre release development core. Fixed.
