### ISSUE TITLE
Get HDMI audio output working

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#138]
Self-explanatory.

Depends on #114

**Comment by gardners** [comment]
Begun implementing this.

Using the hdmidebug target, I am able to play a tone, but it is being  badly shaped, a the following images show:

![Bildschirmfoto vom 2019-11-17 22-20-37](https://user-images.githubusercontent.com/665423/69007182-60a84a00-098a-11ea-8d0c-4553b7544bb1.png)
![Bildschirmfoto vom 2019-11-17 22-19-29](https://user-images.githubusercontent.com/665423/69007183-60a84a00-098a-11ea-88aa-c1ead2ec7a03.png)
![Bildschirmfoto vom 2019-11-17 22-16-21](https://user-images.githubusercontent.com/665423/69007184-60a84a00-098a-11ea-8a18-145c05193c60.png)

The waveform is smooth, just badly enveloped.

Changing the HDMI initialisation frequency in vga_hdmi doesn't change the ~4Hz pulse train, so it is not some HDMI setup thing.

That the waveform is smooth suggests to me that it probably isn't samples being missed, but its hard to know for sure.

**Comment by gardners** [comment]
New fascinating clue: HDMI video works with SPDIF audio enabled, only in NTSC mode: In PAL mode, the screen goes blank.  SPDIF audio is still very broken up in NTSC mode, so something is still not right.

**Comment by gardners** [comment]
Found this nice reference: https://www.av-iq.com/avcat/images/documents/pdfs/digaudiochannelstatusbits.pdf

There should be 192 sample PAIRS per sub-frame, not 192 samples, according to this.  Reading more...

**Comment by gardners** [comment]
But that might be wrong, as with that, there is not even an HDMI image.
What might also be an issue is if the parity bit is 1, then we need the inverted preamble.  It doesn't look like that ever actually gets sent.

**Comment by gardners** [comment]
Another source also indicates 192 x L+R pairs: http://www.hardwarebook.info/S/PDIF
But finding good source material seems to be hard...

**Comment by gardners** [comment]
Trying a different SPDIF implementation from OpenCores in case it solves the problem.

**Comment by gardners** [comment]
So, still no picture with PAL mode when SPDIF audio is enabled.  But still picture NTSC mode, even if audio is enabled.  STill not convinced the audio is right. Will build full bitstream to test with games.

**Comment by gardners** [comment]
Full bitstream: Still no picture in PAL. Picture and broken HDMI audio in NTSC.  Commando music reveals that it seems to be eliminating all high-frequencies.  That is, it sounds like only some samples are being accepted.  Note that this is with a totally different SPDIF implementation to before. This makes me think that something with the ADV7511 setup is wrong.

**Comment by gardners** [comment]
See also commit 910ab4753ccd15754e3a0315c656bd80be01d266

**Comment by gardners** [comment]
I forgot to tag that commit with this issue, but it might well be the fix: Set N and CTS values for the audio stream, so that proper clock recovery is possible by the receiver.  This at least made LOUD noise come out of the headphones with the test bitstream.  PAL video mode is still blank and silent.

**Comment by gardners** [comment]
Build into full mega65r2 target bitstream, and music is now quite recognisable, but still badly distorted using earbuds in the HDMI monitor I have here.  HDMI TV still doesn't want to give a picture in either NTSC or PAL mode, but that might be HDMI interrupt handling, which I have reverted, and will try on a fresh bitstream when ready.

**Comment by gardners** [comment]
I get the distinct impression that the problem is the N and CTS values need fine-tuning.  The best solution to this is to allow reading and writing of the I2C registers of the 7511 directly, as well as the automatic initialisation via the i2c_sender, that way I can fine tune the values without having to do repeated synthesis runs.

**Comment by gardners** [comment]
Apparently it isn't unusual to have problems with Audio Clock Recovery (ACR) in HDMI: 

http://www.aes-media.org/sections/uk/Conf2011/Presentation_PDFs/14%20-%20john%20dawson%20-%20Audio%20Transport%20over%20HDMI%20-%20AES%202011.pdf

This also adds weight to the theory that getting the N and CTS values right is our best hope.  Certianly wrong values (like now) are going to hurt things.

Alternatively, we can increase the sample rate to 44100*(27.083333/27) and rely on the receiver to deal with the 0.31% difference as it would for any normal clock drift.  This would be 44237 samples per second in the SPDIF transmitter.

**Comment by gardners** [comment]
The first option didn't work, so the above commits try the alternative of increasing the sample rate.

**Comment by gardners** [comment]
That didn't work either. So let's take a step back, and implement a full R/W I2C memory mapped interface for the ADV7511, so that we can see what it thinks about the audio etc.
Will need to also add the i2c_sender functionality, so that it can automatically initialise the HDMI TX when required.

**Comment by gardners** [comment]
Going slightly mad trying to get the memory-mapped I2C registers working.  Mapping of the existing M65R2 I2C registers is also being flaky, so suspecting the clock frequency bump might have pushed things out of tolerance, but need to investigate further.  Need a test harness for the I2C stuff, so that I can quickly make sure whether the hdmi_i2c stuff is actually correct or not.

**Comment by gardners** [comment]
ok, with new HDMI I2C control and memory mapping of registers we are back to automatically configuring the HDMI display -- although it doesn't re-configure when monitor turns off or is disconnected, only on initial power up.  Writing to an ADV7511 register does trigger it, however.

**Comment by gardners** [comment]
(The last commit above is a potential fix for this problem).

**Comment by gardners** [comment]
It now mostly works, but the 7511 doesn't get powered back up after HDMI link loss. This means that the screen doesn't come back on automatically if monitor gets turned off and on.  Fix this by checking register $41 in our existing infinite read loop, and powering the chip back up if it has been powered off.

**Comment by gardners** [comment]
Wrote HDMI status debug utility that lets me see things like N and CTS values.  This revealed that detected CTS was double the expected value, indicating we are generating samples at 88.2KHz, not 44.1KHz. Thus we need to double the value of N, and keep CTS the same.

**Comment by gardners** [comment]
Well, that didn't fix it. But being able to play with registers in real-time revealed some things:
1. You have to turn HDMI audio TX off via reg $0A before you can change things like auto/manual CTS.
2. Switching to auto CTS got HDMI audio working very nicely in NTSC! (commits follow)

**Comment by gardners** [comment]
Now to figure out why PAL video still shuts down when audio is enabled...

**Comment by gardners** [comment]
Audio level is still WAY too high for HDMI audio. Mixer values need to be like $0707 or lower, so we are still at least 5 bits too loud.  Also some static in the sound sometimes (e.g., in parts of the krakout music).

**Comment by gardners** [comment]
Static seems to be constant level, i.e., it sounds relatively louder if you reduce audio mixer gain, and quieter if you increase audio mixer gain.

**Comment by gardners** [comment]
Not audible when there is no sound playing. Is it some harmonic of SID to HDMI audio output?

**Comment by gardners** [comment]
For PAL mode, anything that ceases the audio stream restores video, including switching from SPDIF to another audio source, or telling the ADV7511 that the audio source uses external MCLK instead of recovered MCLK.

**Comment by gardners** [comment]
Have gone through all ADV7511 I2C main map registers and confirmed that everything looks right in PAL vs NTSC modes, but PAL mode still shows no video when SPDIF audio is enabled. Running out of ideas as to what could be the cause.

**Comment by gardners** [comment]
Found a possible cause: In PAL video data continues one raster line into the VSYNC period, which might be confusing the ADV7511.  Trying to fix this now...

**Comment by gardners** [comment]
Some TVs/monitors have very broken audio, suggesting we aren't indicating the audio sample format correctly.

**Comment by gardners** [comment]
Varying I2C register 14 doesn't change it.
Is it bigendian/littleendian perhaps?
Or just 192khz audio sample rate?

**Comment by deftmega** [comment]
PAL over HDMI broken on HANNS-G 27" Monitor:
![09D82F11-159D-4234-9067-16F68EAD5658](https://user-images.githubusercontent.com/3924427/76906353-066db600-68a4-11ea-8d7b-c5dc20fbf84e.jpg)

Disabling Audio completely makes it worse and adds flickering!

**Comment by gardners** [comment]
Issue #165 has added perfect 27MHz pixel clock.  I'll see if that doesn't help us get HDMI audio working with the ADV7511 on all monitors.

**Comment by gardners** [comment]
Compatibility test reports are being gathered in:

https://docs.google.com/spreadsheets/d/1Eg2ADZKcW-mgzo7DsoEzXYScAOobrWCLVbrtxMsdCtE/edit#gid=0
