### ISSUE TITLE
HDMI video briefly blinks off sometimes

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#139]
Very likely this is due to the way we update the HDMI I2C registers continuously.  Switching it to instead reconfigure whenever an interrupt is received from the ADV7511 should fix it.

**Comment by gardners** [comment]
Various fixes in #138 may well fix this problem, or at least mitigate it. This includes interrupt driven automatic reenabling of the link, instead of blindly setting the registers 4 times a second.
The blinking could also be due to losing the HDMI link because of out of tolerance timing due to 27.083 vs 27.000 MHz pixel clock, since enabling the audio stream currently totally kills display in PAL mode.

**Comment by gardners** [comment]
Haven't seen this issue for a while.  Will close 20DEC2019 if it is not seen again by then.

**Comment by rdpeake** [comment]
Closing as no comment about it being seen since 20 december 2019
