### ISSUE TITLE
implement hypervisor mode from double-tap-restore

### ISSUE THREAD

**Issue by Ben-401** [MEGA65/mega65-core#14]
currently a hook/handler has been implemented to:
- detect when a double-tap restore-key is made
- enter HYP-mode
- change border color (*)
- leave HYP-mode

It is expected that the functionality at (*) be developed to:
- display a menu on the screen
- provide HYP-mode functionality
- allow clean exit from HYP-mode

**Comment by gardners** [comment]
Some work has been done on this. Note that double-tap RESTORE is now "hold RESTORE for 0.5 - 1 second" (2 - 4 seconds still does reset, and <0.5 seconds, triggers NMI as normal).
