### ISSUE TITLE
Cannot access QSPI configuration flash for updating bitstream under MEGA65 control

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#149]
We want to allow flashing new bitstreams under MEGA65 control for easy upgrade and loading of multiple bitstream cores at the same time.

**Comment by gardners** [comment]
Datasheet for QSPI NOR flash: https://www.cypress.com/file/448601/download

**Comment by gardners** [comment]
Implemented user control of QSPI clock signal and JTAG boundary scanning of pin states as issue #155 .
Should now be able to work on fixing this.

**Comment by gardners** [comment]
Can now access QSPI flash.

**Comment by frehwagen** [comment]
Merged to stable_base/14
