### ISSUE TITLE
HDMI display doesn't not always come on on power-up

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#152]
If an HDMI interrupt happens while initialising the HDMI chip, it will only cause the HDMI configuration to continue, instead of starting over from the beginning.  However, the interrupt may indicate that the HDMI TX chip has reset, and thus needs a full reset.

**Comment by gardners** [comment]
To test, we need to do a large number of reset sequences in a row, and see if it happens.
Will quantify the probability under the bitstreams where it occurs.

**Comment by gardners** [comment]
Seems to happen more often if the monitor has been asleep for a while.

**Comment by gardners** [comment]
e.g., turn monitor off. Turn monitor on, and leave off long enough to go to sleep. 
But that also doesn't always cause it.

**Comment by gardners** [comment]
The turn off M65, turn off monitor for long enough to go to sleep/power saving, and turn monitor back on, and finally turn on M65.
Do a series of runs:  Y = happened, - = means it didn't happen.
----Y----Y-YY

So it looks like the probability is >= 10%.  Twenty runs in a row without problem should be enough to confirm the problem is fixed.

**Comment by gardners** [comment]
Also confirmed that it still happens without turning the screen off first.

**Comment by gardners** [comment]
Seems to have fixed it.
Need to verify it, before retiring the issue.

**Comment by adtbm** [comment]
No proper HDMI signal at all.

Let's start with VGA:
VGA looks nominal:
![2019-12-08 21 49 48](https://user-images.githubusercontent.com/35996116/70396124-4fd97a00-1a06-11ea-99e1-bbcda52036e6.jpg)


OK, main test HDMI:

i can confirm, that the Panel detects the HDMI signal immediately, but no proper picture. several attempts...
Examples:
![2019-12-08 21 49 19](https://user-images.githubusercontent.com/35996116/70396135-7697b080-1a06-11ea-8f20-bb4de27f8400.jpg)
![2019-12-08 21 50 46](https://user-images.githubusercontent.com/35996116/70396136-78fa0a80-1a06-11ea-91f8-3be01b4c8ddf.jpg)
![2019-12-08 21 50 48](https://user-images.githubusercontent.com/35996116/70396138-7ac3ce00-1a06-11ea-9489-841f3f8904b5.jpg)
![2019-12-08 21 50 51](https://user-images.githubusercontent.com/35996116/70396143-7dbebe80-1a06-11ea-807b-9df26ab27042.jpg)

**Comment by adtbm** [comment]
sometimes, i receive a more or less...picture.
![2019-12-08 22 24 42](https://user-images.githubusercontent.com/35996116/70396532-405c3000-1a0a-11ea-9cfb-eb21183bf4ef.jpg)


and even if the picture looks as bad as here:

![2019-12-08 22 24 55](https://user-images.githubusercontent.com/35996116/70396544-55d15a00-1a0a-11ea-8978-34f942560272.jpg)

The Freeze menu works always: Proof:

![2019-12-08 22 25 05](https://user-images.githubusercontent.com/35996116/70396551-6255b280-1a0a-11ea-802e-8e9242c5f0c5.jpg)

**Comment by adtbm** [comment]
All results are with PAL. NTSC seems to work:

![2019-12-08 22 31 06](https://user-images.githubusercontent.com/35996116/70396594-b06ab600-1a0a-11ea-8176-43634ea071ea.jpg)

**Comment by adtbm** [comment]
to summarize it:
The monitor gets the HDMI signal superfast, regardless of in PAL or NTSC !

But in PAL no picture, only freeze menu.
in NTSC picture OK !

**Comment by gardners** [comment]
So I am suspecting that it could be HSYNC polarity that is a problem here.
In any case, it seems to be the HSYNC is being misinterpretted in some way.

Things to try:

sffd307c 0
sffd307c 40
sffd307c 80
sffd307c c0

Those four try all combinations of HSYNC and VSYNC polarity.

Then try disabling HDMI audio:

sffd361a 0

Each of the 8 combinations of the above would also be good to test: If it
is an older monitor, it might not do audio over HDMI well, and so the HDMI
audio could possibly cause a problem.

That's the main ideas I have for possible causes.

Paul.

**Comment by rdpeake** [comment]
"ADV7511 fails HDMI 1.4a compliance tests at 720x576p and 720x480p in our configuration. Fixed on R3 PCB. Wont (and cant) fix on R2 PCB"
