### ISSUE TITLE
Work out how to do multiple bitstreams

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#153]
Explore FPGA reconfiguration, so that we can switch to alternate bitstreams. Both  for handling updates, as well as alternate cores.

**Comment by gardners** [comment]
Hitting a problem with the STARTUPE2 instantiation. Basically the FPGA never completes setup, possibly because of some strange setting with this.  Will debug...

**Comment by gardners** [comment]
Complete and working.

**Comment by frehwagen** [comment]
Merged to stable_base/14
