### ISSUE TITLE
Incorporate fpgajtag functionality into monitor_load

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#155]
monitor_load currently calls the fpgajtag program to actually upload a bitstream to the FPGA.
It would be nice to just roll it into to monitor_load, to make life easier.
Also, it would set the scene for us to be able to add other more interesting JTAG functions, such as boundary scan of pins, or manually overrride pins to debug hardware devices etc.

**Comment by gardners** [comment]
VCD output, including in background now works. Thus we have a complete JTAG boundary scan / signal monitoring environment.

**Comment by frehwagen** [comment]
merged to stable_base/14
