### ISSUE TITLE
Update to new Kick Assembler version

### ISSUE THREAD

**Issue by titanlab** [MEGA65/mega65-core#157]
Kick Assembler releases >= v5.10 now contain new 65c02 instructions. Replace existing macros and migrate to them. This issue can be assigned to myself.

**Comment by gardners** [comment]
Thanks! I have been underway relocating to Arkaroola, and will continue to have intermittent internet for the next 10 days or so.

**Comment by lydon42** [comment]
Current mega65-core uses acme and ca65, I can't find any make rule that requires KickAss.
So this issue can be closed, and essentially KickAss could be removed from the mega65-core repo.

**Comment by lgblgblgb** [comment]
My personal opinion only: it's not a good thing to always change assembler according to the latest fashion :) Just my personal experience, that Xemu used the Ophis format for some hypervisor debug symbol mode. Then mega65-core switched to acme for hyppo. Ok, now I altered things for acme (and I plan to use the "rep" file as well not only the "sym"). Then now switching to kickass, another change? :( Though for sure, I more speak about the assembler used for assembling hyppo.

**Comment by titanlab** [comment]
I also think this issue can be closed. KickAss is also not open-source anymore.

**Comment by lydon42** [comment]
I also discussed this with paul, we will remove KickAss from the core repo as it is not required anymore.

**Comment by lydon42** [comment]
Removed in hwsc.
