### ISSUE TITLE
CPU and freeze glitching on recent bitstreams

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#158]
From C65 mode:

MONITOR
M6000

and it will display a couple of rows and hang.

Also, going into freeze menu and trying to resume barfs. 

It seems the CPU has problems with access memory around $6000.

Last build from 2019 is fine. First ones from 2020 are broken.  
Looking at git diff shows only VDC emulation and GeoRAM stuff changed in CPU.  So explore VDC emulation as probable cause.

**Comment by gardners** [comment]
Last known working commit: 5ae744e 
First known non-working: e785e32

**Comment by gardners** [comment]
Removing VDC emulation doesn't fix it. But removing both VDC and GeoRAM does.

**Comment by gardners** [comment]
(Freeze menu then behaves correctly)

**Comment by gardners** [comment]
Confirmed that it was the GeoRAM mapping that was the problem, i.e., the VDC code can be returned to use safely.

**Comment by bluewaysw** [comment]
Relates to this fix on the #141 branch:
https://github.com/MEGA65/mega65-core/commit/9b45fb11e035bba8a6973ae932430e65036c2130

**Comment by gardners** [comment]
@frehwagen worth merging this onto stable_base once you are happy with it.
