### ISSUE TITLE
ROM checksum in Hyppo sums wrong region of memory

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#167]
It doesn't set the MB part of the MAP, so reads from some unmapped memory somewhere.

**Comment by gardners** [comment]
Fixed. @frehwagen another to merge into stable_base when you are happy with it.
This should also slightly improve boot time, as it was checksumming unmapped memory, which can have a timeout of hundreds of cycles for each access.

**Comment by frehwagen** [comment]
Merged into stable_base/14.
