### ISSUE TITLE
Implement scripts for auto-generating test script document

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#175]
We want to have a semi-automatically generated test script for confirming the correct function of the MEGA65. 
We want to ensure that such documentation has full coverage of all known issues.
To do this, we will read special fields from the body of each issue on github, to generate a list of things that SHOULD get tested.  These tags will be searched for in a special latex file that will be used to generate the actual latex for the test script, which will then be turned into a PDF.  Any tags that have not been mentioned in the latex file will be listed at the end of the document as "functionality and past problems not currently covered by this test procedure".

**Comment by gardners** [comment]
The format for the special fields is:

##BREAKS Description of what doesn't work.

e.g.:

##BREAKS MEGA65 fails to produce display on VGA port

These fields MUST be in the body, i.e., the first block of text in the issue (so, for example, these here won't show up).  They can be added after the event by editing the text block.

**Comment by lydon42** [comment]
This is now #593
