### ISSUE TITLE
External SD card slot should be the default

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#176]
Currently, if you have an internal SD card fitted, it takes priority over the external slot.
However, it seems more likely that people will want to be able to have an internal card, and then sometimes plug in an external one, and then expect that the external one will take precedence.

##BREAKS External SD card will be used in preference over internal SD card when booting
##BREAKS External SD card will be used in preference over internal SD card in flash menu

**Comment by frehwagen** [comment]
Fixed as part of #156, merged into stable_base/14.
