### ISSUE TITLE
refine checkpoint messages

### ISSUE THREAD

**Issue by Ben-401** [MEGA65/mega65-core#18]
i want the checkpoint messages modified so that:
- they are shorter
- they primarily display the checkpoint TEXT payload
- checkpoint text payload increased in number of chars it supports.

**Comment by Ben-401** [comment]
refer to: https://groups.google.com/forum/#!topic/c65gs-development/Gzm1z2FIcjA
for a discussion...

**Comment by rdpeake** [comment]
Memory available in hypervisoer insufficient to support more complex messages
