### ISSUE TITLE
1Mhz and 2Mhz clock does not appear to be accurate (SynthMark)

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-core#183]
Stable_base-13:

Synthmark reports 0.94x or 0.95x in 1MHz mode and 1.95x in 2 MHz mode with (default) PAL. NTSC seems to be sigificantly lower but cannot be tested due to machine locking up.

![9F2BAFAB-AB2B-4B2F-9BBC-BF78219BF740](https://user-images.githubusercontent.com/3924427/77161057-0985c380-6aa9-11ea-8e2a-70b8e832cfad.jpg)

![108299C9-8193-4DDD-8E81-158A91C5CF25](https://user-images.githubusercontent.com/3924427/77161078-19050c80-6aa9-11ea-9eb4-52f826a66fa1.jpg)

**Comment by lydon42** [comment]
I can't get synthmark running, so I can't check. Is this still a problem @deftmega ? If not, please click on close.
