### ISSUE TITLE
too many empty lines in hypervisor during bootup

### ISSUE THREAD

**Issue by adtbm** [MEGA65/mega65-core#191]
during bootup there are too many empty lines in the Hypervisors info display, between
DISC-COUNT and
MEGA65.D81 image....... (I think it's 3 empty lines)

due to this, some of the information is scrolling out of the display.

Also the Bitstream version is not visible, when holding CTRL during bootup (probably due to this)

**Comment by adtbm** [comment]
![2020-03-30 01 32 53](https://user-images.githubusercontent.com/35996116/77865051-a294a700-722c-11ea-8745-a5c273abfeda.jpg)

![2020-03-30 02 00 05](https://user-images.githubusercontent.com/35996116/77865064-ad4f3c00-722c-11ea-96b7-46b9fecae3d3.jpg)
![2020-03-30 02 00 14](https://user-images.githubusercontent.com/35996116/77865066-b213f000-722c-11ea-93ed-3fd7d96bee6a.jpg)

**Comment by rdpeake** [comment]
![image](https://user-images.githubusercontent.com/3162788/109422515-c7d8f900-7a2b-11eb-98d1-e1ed4787e97f.png)

current ctrl boot screen no longer has empty lines and shows a fair bit more details
