### ISSUE TITLE
MEGA65 Configure Utility can't recover from corrupted SYSPART contents

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#194]
If it is unhappy, it will report "A version mismatch has been detected!", but not give an option to write out a good config partition with default values.

**Comment by gardners** [comment]
Implementing revised message in this case, and allowing pressing F14 to reset settings to default.

**Comment by rdpeake** [comment]
F14 reset appears to be on development branch - should reopen or create new issue if it doesn't work as intended
