### ISSUE TITLE
microSD card should take priority over internal SD card

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#195]
At present the internal SD card takes priority over the external microSD card slot, but it should be the other way around, so that user's don't get surprised when inserting a microSD card finding it gets ignored.

**Comment by gardners** [comment]
Duplicate of #176

**Comment by gardners** [comment]
Further progress will be on #176, in particular switching the bus in megaflash.c, so that it still defaults to using the external bus.  Or perhaps we should make it scan BOTH busses and show what is on the both...

**Comment by frehwagen** [comment]
Fixed as part of #156, merged into stable_base/14.
