### ISSUE TITLE
Support for German and selected other international/weird symbols

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#196]
It would be nice to be able to type German special letters etc, since ~1/3 the interest for the MEGA65 comes from German-speaking countries.  

Implementing much of the Unicode Latin1 page via chords with the ALT key (and ALT+shift, where it makes sense) seems the easiest way to do this.

**Comment by gardners** [comment]
This will also require implementing the missing 128 symbols for our ASCII type face.

**Comment by gardners** [comment]
NOTE: It is the DOS-style Latin1 codes that are generated, not UTF8-compatible codes that get generated.  This is unlikely to change.

**Comment by gardners** [comment]
We have the first Latin1 supporting font in FDISK now, so we can begin to test this.
The keyboard layout is all over the shop, and CAPS LOCK has inverted meaning, and shift is ignored, so there is some fixing to be done there...

**Comment by frehwagen** [comment]
Fixed as part of #156, merged into stable_base/14.
