### ISSUE TITLE
ESC, F9, F11, F13 and TAB keys in ASCII key scanner have no delay before repeating

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#197]
Try pressing any of these keys in FDISK when prompted to type, and you will see this problem.
All are suspiciously on the last column of the keyboard scanner.

On-screen keyboard shows these keys as not being solidly on, so the problem is very much real and observable. 

Keys look to be held about 1/4 of the time.

##BREAKS ESC, F9, F11, F13 and TAB keys repeat at normal rate in ASCII keyboard scanner

**Comment by adtbm** [comment]
Not sure, if this is related.
when pressing the above mentioned keys, wrong & strange symbols showing up.
Also when usuing standard keys, it looks like the letters are slowly shifting from left to right.
Have a look at the attached picture.

**Comment by adtbm** [comment]
![2020-04-07 18 33 35](https://user-images.githubusercontent.com/35996116/78695635-a5635c00-78fe-11ea-938f-cfd3df5d4155.jpg)

**Comment by frehwagen** [comment]
Fixed as part of #156, merged into stable_base/14.
