### ISSUE TITLE
when typing letters, they are getting displayed "shifted"

### ISSUE THREAD

**Issue by adtbm** [MEGA65/mega65-core#199]
when repeatedly typing the same letter, it looks like, the letter is getting displayed slightly shifted every time.

please check this picture:
![2020-04-07 18 58 11](https://user-images.githubusercontent.com/35996116/78698241-561f2a80-7902-11ea-9677-91071fa89f3d.jpg)

**Comment by gardners** [comment]
Which bitstream? PAL/NTSC? VGA/HDMI?

**Comment by gardners** [comment]
If it is the #156 fix bitstream, then I wouldn't worry about it, as it will get totally re-worked when the revised HDMI mode stuff gets pulled in.

**Comment by frehwagen** [comment]
Do you know, can you explain what exact change fixes this from the changes we consider HDMI rework?

**Comment by gardners** [comment]
The problem shown above is due to the old display mode stuff. It should completely go away with the HDMI rework, so I think we can just close this issue as "fixed by unmerged changes", and only worry about it if it reappears.  If you agree, just close it.

**Comment by adtbm** [comment]
Rechecked the issue.
it is bound to the general HDMI/VGA rework requirement.

The bug only appears in VGA NTSC all others are fine

**Comment by lydon42** [comment]
I can't see this on nexysA7 VGA, neither with master, nor development/hwsc. Checked PAL/NTSC, CRT emulation on/off, everything looks fine.
Closing.
