### ISSUE TITLE
Switching from NTSC to PAL and then back to NTSC will lock up machine

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-core#201]
Encounterd in 156/65: Switching from NTSC to PAL and then back to NTSC via freeze menu will lock up machine. Afterwards hitting reset button will garble screen but not reset.

**Comment by frehwagen** [comment]
Duplicate of #181?

**Comment by gardners** [comment]
Looks like in NTSC mode raster interrupts are not generated for raster lines 0 to 5.
