### ISSUE TITLE
Machine locks up with cartridge inserted

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-core#202]
Encounterd in 156/65: Machine won't boot if cartridge is inserted. Also not possible to run flash or any other menu. Blue screen with interesting white block visible.

**Comment by deftmega** [comment]
This is still the case for easyflash. Behavior changes on each reset (reproducible) until menu appears. Can't start any title tho. Other cartridges e.g. Sam's Journey work.

**Comment by deftmega** [comment]
easyflash 2 is no longer working. this is still the case. Sam's Journey and super breadbox work. We will look into this later.

**Comment by lydon42** [comment]
this is a #564

**Comment by lydon42** [comment]
Ultimax boot works with [3fcf2de](https://github.com/MEGA65/mega65-core/commit/3fcf2deceaada30f1a8e1b219eb943e737211d65)
This is a duplicate of #684
