### ISSUE TITLE
vdc_mem_addr timing closure is -18ns

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#205]
We probably need to add a wait-state to VDC memory accesses, so that the address translation has an extra 25ns clock tick to calculate the address.

**Comment by frehwagen** [comment]
Looks this already has been fixed on branch #165?

**Comment by gardners** [comment]
If not on 165, it certainly is on 138-hdmi-audio-27mhz
Please test that the VDC access still works correctly before closing.

If GEOS doesn't runn on this branch, we should write a little VDC emulation test using CC65.
