### ISSUE TITLE
SDHC cards of 16GB or larger don't like ACMD41 initialisation

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#215]
SDHC cards don't like the ACMD41 initialisation sequence, as it makes them think the host is SDC only, and so they allow access to only a small fraction of the storage. (See https://electronics.stackexchange.com/questions/358114/sd-card-block-read-write-issue-in-spi-mode-stm32-cmd17-cmd24 )

So will try to fix this.

##BREAKS 16GB SDHC card capacity correctly recognised in FDISK

**Comment by gardners** [comment]
Note this seems to mostly be a problem with the external microSD slot. 8GB and 16GB cards work on the internal slot for me, but neither properly on the external slot.

**Comment by gardners** [comment]
Seems to work, but there was actually a problem in FDISK that was also responsible.

**Comment by lydon42** [comment]
Tested with latest prerelease devel@fc504ef and 920283: 16GB µSDHC is correctly detected and used in external slot.
