### ISSUE TITLE
Issue with RESTORE key for invoking the freeze menu

### ISSUE THREAD

**Issue by RalphEgas** [MEGA65/mega65-core#216]
***
This was refiled. Originally created in MEGA65/mega65-freezemenu,. @gardners requested it to be refiled here:
"Please refile on the mega65-core repo, as this is a problem with the hardware triggering the freeze menu, not with the behaviour of the freeze menu."
***

Holding the RESTORE key for 1s for the first time does not bring up the freeze menu. Only after doing this once and then doing it again will in fact bring up the freeze menu. From that moment onward the feature will work as advocated until the machine is reset (soft or hard) at which point it will take one extra hold-for-1-second before it works again.

**Comment by rdpeake** [comment]
restore key on my dev kit seems to be working - closing for now, but if still persistent on your end reopen it.
