### ISSUE TITLE
Allow querying and setting of real time clock from MEGA65 Configure

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#222]

**Comment by gardners** [comment]
Implemented. Should be tested for consideration for merging onto stable_base.

**Comment by gardners** [comment]
As suggested improvement is to always use 24 hour time, and hide bit 7 of the hour, to make it less confusing for users. Probably not a bad suggestion.

**Comment by adtbm** [comment]
Tested #222 - 1
Bitstream used: mega65r2-20200527.10-HEAD_n-a9ccc62+DIRTY.bit

Main Test - RTC clock
- Setting the RTC clock works
nicely implemented in the Settings menu. 24hr time format

Things noticed:
- Defts Demo crashes/freezes MEGA65, see pictures

- PAL
![2020-05-28 01 19 53](https://user-images.githubusercontent.com/35996116/83081636-6d1c0680-a081-11ea-8849-d9678cdd0fe9.jpg)

-NTSC
![2020-05-28 01 14 37](https://user-images.githubusercontent.com/35996116/83081665-786f3200-a081-11ea-8264-b340e16b2940.jpg)

Using 165-88 as reference: Demo works.

**Comment by gardners** [comment]
The problem is some VIC-IV issues that have already been fixed in #165 branch. i.e., it is not a blocking problem that the demo doesn't work.

**Comment by frehwagen** [comment]
Merged into stable_base for release @stable_base/16, this includes #207 fix as well.
