### ISSUE TITLE
resolve what are the dependencies of this project? ubuntu/windows/mac

### ISSUE THREAD

**Issue by Ben-401** [MEGA65/mega65-core#236]
This issue is based on #233.
It is understood that best branch to build is currently ```stable_base```.

I want to update the documentation (currently docs/build.md) to describe what prerequisite packages are required to completely build this project.

I will look at Ubuntu-16 and Ubuntu-18, then Ubuntu-20.
I do not have easy access to mac or windows.

Currently I think I have all the packages required, just making an issue to tag against.

**Comment by Ben-401** [comment]
done u18, now doing u16, will rebase/squash before PR.

**Comment by Ben-401** [comment]
after this PR is merged into stable_base, would you consider merging stable_base into master?

**Comment by lydon42** [comment]
18 is long gone... new issue for 22?
