### ISSUE TITLE
Convert HYPPO to use open-source ACME assembler

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#260]
KickAss is great, but its closed source. Also, it is written in JAva, so can't (eventually) be ported to run native on the MEGA65.  Finally, ACME has 1st class support for all MEGA65 CPU features, so it makes it a logical choice.

**Comment by gardners** [comment]
Now boots to BASIC 10 and does disk mounting etc with ACME-compiled HICKUP.
Ready for staging for merging.

**Comment by Ben-401** [comment]
In branch 138-hdmi-audio-27mhz, the use of the ACME compiler is used in place of the KickAss.
But how to install ACME? can it be a submodule from github?
And should that branch also remove the KickAss files? i think so

**Comment by Ben-401** [comment]
https://github.com/meonwax/acme
https://sourceforge.net/projects/acme-crossass/

**Comment by gardners** [comment]
Yes, by all means produce a pull request adding auto-compilation of ACME

**Comment by lydon42** [comment]
KickAss is removed and no longer used, HYPPO uses acme.
