### ISSUE TITLE
HyperRAM: Very first control register read needs two reads

### ISSUE THREAD

**Issue by sy2002** [MEGA65/mega65-core#281]
When I use a freshly programmed FPGA (fresh HyperRAM controller), and then read the control registers, the value of the first read at the first control register is wrong:

```
Control Registers:     (Output should be: 0081, 000C, 00F6, 00FF)
00DE
000C
00F6
00FF
```

When I then restart the same test program (without reset/restart, etc., just run the test program again), then the values are all read correctly:

```
Control Registers:     (Output should be: 0081, 000C, 00F6, 00FF)
0081
000C
00F6
00FF
```

I did an experiment:

If I read the very first value of the very first control register two times instead of one time, then I am receiving the correct value, even if I did it directly after programming the FPGA.

**Comment by sy2002** [comment]
Retested this issue with the new version from https://github.com/MEGA65/mega65-core/issues/280#issuecomment-699468911:

The problem still persists.

**Comment by lydon42** [comment]
same as #280
isn't this old news? @sy2002 @gardners

**Comment by gardners** [comment]
As for #280 I think we can close it. Users shouldn't access those registers, anyway.
