### ISSUE TITLE
Hyppo: Freeze menu breaks text mode display after switching to lowercase

### ISSUE THREAD

**Issue by steph72** [MEGA65/mega65-core#286]
Steps to reproduce:

1) boot MEGA65 into C65 mode
2) press RESTORE to enter freeze menu
3) press "f3" to resume
4) type: PRINT CHR$(14) [ + RETURN ]

Result: "@" characters all over the screen (colours remain correct though)

Also works in C64 mode. Also works when entering lowercase with [MegaKey]+[ShiftKey]

**Comment by gardners** [comment]
This is already fixed with all the $DD00 bank bit fixes in the head of 138-hdmi-audio-27mhz

**Comment by lydon42** [comment]
Bug can not be triggered with above recipe in mastet@bbd0391 on r3.
