### ISSUE TITLE
There is no wifi-capabilties in the mega 65 fpga

### ISSUE THREAD

**Issue by anshul-birajdar** [MEGA65/mega65-core#288]

**Comment by gardners** [comment]
Correct. The current recommended way to add wifi to a MEGA65, is to use the ethernet port to connect to a cheap little wireless router, like a GL-INET AR150 or a cheap TP-LINK one.

**Comment by anshul-birajdar** [comment]
Can you please demonstrate how to connect to wifi and use the network?

**Comment by gardners** [comment]
Connect the ethernet port via an ethernet cable to a wifi router.

**Comment by gardners** [comment]
(but note that we don't have any finished networking software for the MEGA65 yet. This will come in coming months.)

**Comment by lydon42** [comment]
Not a bug, not a feature that is going to be implemented. Closed.
