### ISSUE TITLE
Sprite data pointer can be changed mid-sprite

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#293]
Lots of C64 software relies on the feature that the VIC-II latches the sprite pointer value at the start of drawing a sprite.
MEGA65 currently allows changing it at any time. This needs to be made compatible with VIC-II behaviour.

Commando title screen shows doubled sprites for example as a symptom of the problem.

**Comment by lydon42** [comment]
This is not fixed. With latest pre release development I still have a broken title screen. COMM and last bit of O are shown above the actual title position again. Also the Text in the footer seems broken.

**Comment by lydon42** [comment]
I don't think that there is still a sprite problem in RC1, It looks more like a raster problem? Lower part of the screen should be black showing "PRESS FIRE TO START", but I see the graphics going down all the way instead.

So I close this as solved (COMMANDO title sprites look fine).
