### ISSUE TITLE
Vivado 2020.1 complains of multiple drivers for reg_math_write

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#298]
See above.  Will split the logic using a toggle to cross the process boundaries.

**Comment by gardners** [comment]
Interestingly older versions of vivado worked with this. I'm guessing its because the logic can actually be implemented using an SR flip-flop with the S and R controlled from different clock domains.  But anyway, it's not hard to fix.

**Comment by lydon42** [comment]
Can't find this error in any recent logs, closing.
