### ISSUE TITLE
Speaker output is very noisy

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#305]
Lots of high-frequency noise on the speaker output lines, which should not be there.

Amplifier chip says -70dB cut-off at 26KHz, but we are seeing square-wave noise at several MHz.

Looks like 10.1MHz on MCLK instead of 6.144MHz.  First step is to try to fix that.

**Comment by lydon42** [comment]
This is merged.

**Comment by gardners** [comment]
See also #820, which improves on this further through providing a low-pass filter
