### ISSUE TITLE
Bug in instruction ASW

### ISSUE THREAD

**Issue by Edilbert** [MEGA65/mega65-core#306]
The ASW instruction does not shift bit 15 of the 16 bit word into carry, as it should.
Example: code for 32 bit left shift
```
>001700 FF FF 00 00

A 001710 CB 00 17 ASW $1700
A 001713 EB 02 17 ROW $1702
A 001716 00       BRK

G 801710
BREAK
M 1700
> 001700 FE FF 00 00
```

**Comment by gardners** [comment]
Implementing a fix now.

**Comment by lydon42** [comment]
All test successfully passed.
