### ISSUE TITLE
internal discdrive on DevKit release bitstream not working

### ISSUE THREAD

**Issue by adtbm** [MEGA65/mega65-core#307]
It's not possible to load something from internal drive.
If you switch in CONFIGURE to internal drive it still loads the content of the SDcard
If you switch in FREEZER to internal drive it starts loading, but fails.  blinking Drive LED or ?FILE NOT FOUND ERROR.

**Comment by gardners** [comment]
Problem is caused by ROM DOS toggling bit 2, which changes the selected drive, and the logic comparing with the previously selected drive, instead of the currently selected drive.

**Comment by lydon42** [comment]
This is now working with pre release rom and devel bitstream.
