### ISSUE TITLE
BUG - Full color text mode : Color 255 displaying as Color 0

### ISSUE THREAD

**Issue by smnjameson** [MEGA65/mega65-core#310]
When using full color text mode and displaying a tileset, Color 255 seems to be using Color 0 instead. Note the camera shot of the hardware output below displays black pixels, changing Color 0 values to say red will display these pixels as red also. 

The second picture below shows the same scene but captured via m65_connect with  the correct pixel values in this area indicating that the m65_connect renderer is getting the correct values whereas the hardware renderer is not.

![](https://cdn.discordapp.com/attachments/719326990221574168/782284376124948490/IMG_20201128_163746.jpg)
![](https://media.discordapp.net/attachments/719326990221574168/782284491196465181/mega65-screen-000001.png)

**Comment by gardners** [comment]
This is a feature that is poorly documented, and not implemented in the m65/m65connect screen capture:

Colour $FF is taken from the screen RAM, i.e., the "character colour" information.  

If you are using 16-bit text mode, this means you can freely select any of the 256 colours to be colour $FF.  

If you want to ignore this feature, fill the colour RAM values with $FF for the screen, and it will act as though it doesn't exist.

What we need to do is to fix m65 to match this behaviour, and also to complete the documentation of the VIC-IV to explain it.
