### ISSUE TITLE
Raster Rewrite Buffer clarification of behaviour

### ISSUE THREAD

**Issue by smnjameson** [MEGA65/mega65-core#312]
**Scenario**

- Screen is 40 column wide using 16 bit per char and FCM for chars >$ff
- Screen Logical row size is 84 bytes 
- Columns to display per row is 42

Each row contains:

1. 40 FCM chars filling the full width of the screen, color ram for these locations set to $0000
2. Raster rewrite marker in ColorRam = $0090,   ScreenRam = X value from a sinus curve
3. Single Char <$FF corresponding to the row number, ColorRam set to $0d00 (White in this palette)

Resulting view:
![image](https://user-images.githubusercontent.com/4640763/100630005-e3940c80-3321-11eb-9a20-c81d2856b4c8.png)

I wonder if this is correct behavior, as in order to maintain anything drawn after the "final resting position" of the raster along the X, I currently need to draw a terminating char at the far right, making the row makeup as such:

- Screen Logical row size is 88 bytes 
- Columns to display per row is 44

1. 40 FCM chars filling the full width of the screen, color ram for these locations set to $0000
2. Raster rewrite marker in ColorRam = $0090,   ScreenRam = X value from a sinus curve
3. Single Char <$FF corresponding to the row number, ColorRam set to $0d00 (White in this palette)
4. Raster rewrite marker in ColorRam = $0090,   ScreenRam = 320 (at edge of right border)
4. Any char to allow the raster to finish traverse the entire screen width 

Which does produce what I had assumed the original layout would produce:
![image](https://user-images.githubusercontent.com/4640763/100629915-c3fce400-3321-11eb-885b-ea8957cf20e9.png)

**Comment by lydon42** [comment]
Sorry, I can't see what the issue is here. If this is meant to be documentation it should go into the manual, the wiki or a filehost article.
Is this the "you need to put a final RRB with pos > screen width so the whole line is rendered?" thing? I guess everybody knows that by now, right?
Please reopen or refile and make the issue we should be handling clearer. :)
