### ISSUE TITLE
MEGA65 Configuration

### ISSUE THREAD

**Issue by umueller-wsw** [MEGA65/mega65-core#313]
There are still problems in the configuration menu. In my opinion the time is not read correctly from the RTC. After 11:59.00 comes 32:00.01 ? After 23:59.59 comes 24:00.01 ?

Once the menu has been saved you can no longer access the device. Only after switching it off and on again everything works again. Maybe Paul has a good idea again.

**Comment by lydon42** [comment]
Antique issue
