### ISSUE TITLE
Using rewrite transparency on FCM chars causes the alpha mask to be inverted

### ISSUE THREAD

**Issue by smnjameson** [MEGA65/mega65-core#314]
BITSTREAM: mega65r3-20201201.06-138-hd-d0baeedDIRTY.bit

![image](https://user-images.githubusercontent.com/4640763/100674422-042d8800-335d-11eb-83d3-2e58a3c25217.png)

The above picture shows a 40 char wide FCM display with 16 extra rewritten chars per line. The rewritten chars are also FCM, note the red border around these chars, red is color 0.

Therefore you would expect that when setting the vertical flip bit when doing GOTOX for rewrite. That the red color would be made transparent, however the opposite happens and everything BUT the color 0 is made transparent:

![image](https://user-images.githubusercontent.com/4640763/100675227-73f04280-335e-11eb-9450-79e3fb32b36d.png)

This seems to only happen in FCM mode as using the same transparency bit when using normal single color chars works correctly:

![image](https://user-images.githubusercontent.com/4640763/100675164-57eca100-335e-11eb-821d-a2d936ea97a1.png)

**Comment by lydon42** [comment]
RetroCogs confirms that this can be closed on [discord](https://discord.com/channels/719326990221574164/977076334297743360/1274897179768782892).
