### ISSUE TITLE
Error in the configuration menu

### ISSUE THREAD

**Issue by umueller-wsw** [MEGA65/mega65-core#315]
If there are SD cards in both slots the errors happen - the mouse is not recognized and the video mode is not saved correctly. If you only work with one (e.g. internal) SD card everything works fine.

**Comment by gardners** [comment]
ah, ok. This is most likely that configure is accessing the wrong SD card for the config info.  Thanks for working this out.
We need to fix all that, so that it uses the same SD card as the machine when booting.
