### ISSUE TITLE
Pac-Mania game screen badly distorted

### ISSUE THREAD

**Issue by FeralChild64** [MEGA65/mega65-core#316]
The Pac-Maina (https://www.lemon64.com/?mainurl=https%3A//www.lemon64.com/reviews/view.php%3Fid%3D615 ) screen is badly distorted, so that the game is unplayable:
- the playfield shakes
- lives left are not displayed properly
- sprite positions are off
- etc.

![pacmania](https://user-images.githubusercontent.com/48332137/101286706-50107f00-37ec-11eb-8364-ea8922141a29.jpg)

**Comment by gardners** [comment]
Was the MEGA65 in the correct PAL/NTSC mode?
Was IO mode in C64 or C65 or M65 mode?

**Comment by FeralChild64** [comment]
I've checked once again - it's set to PAL, as it should for this game. I used the C65 ROM supplied with the DevKit, in C64 mode (tried both starting machine with C= and switching to C64 mode via GO64) - so I guess IO mode should be C64.

**Comment by lydon42** [comment]
Just checked with pre release development core on r3: it's not the same bad, but different. Only the score lines seem to be doubled but the play area scrolls fine.
Also the freezer freezes.
![20220103_170554](https://user-images.githubusercontent.com/16632479/147953113-39156600-9dd1-43fd-a413-04bba415706d.jpg)

**Comment by lydon42** [comment]
The C64 Mode is not completely compatible that is to be expected, use C64 core instead.

**Comment by gardners** [comment]
Agreed. this is related to the VIC-IV badline handling fu, that is known to have problems. Boulder Dash shows this even worse. C64 core is the workaround for now.
