### ISSUE TITLE
FDISK/FORMAT Utility formats SDCARD and fails check for "DELETE EVERYTHING"

### ISSUE THREAD

**Issue by mindrail** [MEGA65/mega65-core#320]
This has been tried on the shipped devkit bitstream as well as mega65r3-20201214.11-138-hd-3ee0194.bit

This has also been tested with the external and internal sdcards.

Anything that is typed into the safe/warning field gets accepted as permission to format the SDcard.

![mega65-screen-000004](https://user-images.githubusercontent.com/29457753/102339792-9b454180-3fe5-11eb-8e6b-64376113e124.png)
![mega65-screen-000005](https://user-images.githubusercontent.com/29457753/102339795-9c766e80-3fe5-11eb-8068-3ec336ff05cf.png)

**Comment by gardners** [comment]
Confimed and problem found in the mega65-fdisk repo where it is issue #8 (missing `else` in an `else if` clause). 
Fix will be included in next build.
