### ISSUE TITLE
Erasing flash slots not working on Nexys 4

### ISSUE THREAD

**Issue by headkaze** [MEGA65/mega65-core#322]
Launching slot 0 works with the latest **138-hdmi-audio-27mhz** branch but erasing a slot or flashing a bitfile to a slot is failing (see attached screenshot).

Also the nexys4.xdc and nexys4ddr.xdc files need ConfigRate changed from 66MHz to 26MHz so flashing to QSPI from Vivado works without CRC errors.

`set_property BITSTREAM.CONFIG.CONFIGRATE 26 [current_design]`

![PXL_20201128_234312459](https://user-images.githubusercontent.com/1698401/102645798-06e7f580-4131-11eb-8801-bb894023c5ec.jpg)

**Comment by lydon42** [comment]
Duplicate #348 ?
nexys4.xdc and nexys4ddr-widget.xdc both have the 26MHz setting. Note that nexys4ddr target is obsolete, please use the -widget variant.

Can you please test with a recent (today) development core?

**Comment by lydon42** [comment]
#522
