### ISSUE TITLE
Sprite X-position issue in H640 mode

### ISSUE THREAD

**Issue by lgblgblgb** [MEGA65/mega65-core#33]
In my "wannabe CP/M emulator" for M65 I discovered the issue, that sprites' horizontal coordinate is not there where it should be. I can be wrong, but AFAIK, sprite position etc should be independent of the used video mode. So I used the same theory to calculate the X coordinate as it would be on C64 (or so ...) but the sprite then is far too be right compared to where it should be. You can see the issue in this video (around 0:35), the "cursor" I use there is a sprite for real, and I calculate its position from the text coordinates:

https://www.youtube.com/watch?v=iJwvp6lZ2DU

**Comment by frehwagen** [comment]
This might be addressed with the pull request https://github.com/MEGA65/mega65-core/pull/34

**Comment by rdpeake** [comment]
fixed via `H640 flag for sprites to change sprite resolution`
