### ISSUE TITLE
Transparency Issues with 16 color sprites

### ISSUE THREAD

**Issue by smnjameson** [MEGA65/mega65-core#332]
Reduced a bug I was seeing down to the following reproducable test. As you can see overlapping sprites in 16 color mode (16bit pointers, Color 0 set as transparent) seem to have issues:

https://user-images.githubusercontent.com/4640763/103364107-cf743400-4ab4-11eb-8c7d-3e6b80a93d1c.mp4

Tet prg here:
[SpriteTest.zip](https://github.com/MEGA65/mega65-core/files/5754725/SpriteTest.zip)

**Comment by gardners** [comment]
Most curious. Are you able to quantify more exactly what is happening?  It looks like pixels to the left of the overlap are ending up black (or maybe some other colour).  Maybe if you can make a programme that shows the problem statically (maybe hit space to toggle the problem-causing-overlap), then I can dig into it a bit more easily.

**Comment by smnjameson** [comment]
It seems to be that in an overlapped area, the sprite underneath takes the left most column of pixels in the underlying area and repeats them for each column in the overlap, in this case showing black for transparency was in the left most column. The following update to the test will move the sprite to the same position when you press fire:

![image](https://user-images.githubusercontent.com/4640763/103417300-12e8a400-4b82-11eb-81b6-81b7cdbe19f6.png)

[SpriteTest.zip](https://github.com/MEGA65/mega65-core/files/5757675/SpriteTest.zip)

**Comment by gardners** [comment]
Seems to fix it for me. Please confirm in latest bitstream, then mark STAGED.
Test programme for exercising this issue is in github.com/mega65/mega65-tools /src/tests/test_332.c

**Comment by gardners** [comment]
Test written in mega65-tests src/tests/test_332.c

**Comment by lydon42** [comment]
Checked with stable bitstream on r3 hardware, all looks good!

**Comment by lydon42** [comment]
Correct: ![Screenshot 2022-07-31 21-11-05](https://user-images.githubusercontent.com/16632479/182041591-680f3060-085b-4175-832d-a1a3d2e5a706.png)
Wrong: ![Screenshot 2022-07-31 21-11-33](https://user-images.githubusercontent.com/16632479/182041598-0b20fcc5-d8e8-40fb-98e7-d85b8980fbc1.png)
(wrong example made with mega65r3-20201226.18-138-hd-7534ac3.bit)
