### ISSUE TITLE
256 colour substitution not working, only 16

### ISSUE THREAD

**Issue by M3wP** [MEGA65/mega65-core#334]
In colour RAM, you have the ability to do colour substitutions such that the foreground colour can be replaced by any other colour by use of particular bytes.

This facility is not functioning as expected in 256 colour mode.  Furthermore, it is only possible to display 256 colours by use of this facility and so full 256 colour substitutions could be considered necessary.

**Comment by gardners** [comment]
Test written in mega65-tests src/tests/test_334.c
