### ISSUE TITLE
Please enable advanced blinking option for drive LED

### ISSUE THREAD

**Issue by M3wP** [MEGA65/mega65-core#335]
It would be convenient if the drive LED could be caused to flash RED for errors instead of green in order to differentiate between successive file accesses and an error state.

I believe that it would draw more attention to the fact that there is an error, as a point of difference.  Also, I think it would be a touch of distinction for the MEGA65 (having LEDs that are capable of a great deal).

**Comment by lydon42** [comment]
Merged with master.
