### ISSUE TITLE
Switch bitplane memory to bank 4 and 5

### ISSUE THREAD

**Issue by Edilbert** [MEGA65/mega65-core#336]
Currently bitplanes, BASIC program and BASIC variables must coexist in bank 0 and 1 and limit the use of graphics substantially. It would unleash the graphic power to move bitplane memory to bank 4 and 5, either hardcoded or by means of a switch.

**Comment by gardners** [comment]
Bits 0 to 2 of $D07C will allow selecting which 128KB region of chipram the bitplanes are fetched from.
