### ISSUE TITLE
RRB GOTOX is off by 1

### ISSUE THREAD

**Issue by smnjameson** [MEGA65/mega65-core#337]
When setting a GOTOX position of X=0 the next RRB layer actually starts drawing at X=1

![image](https://user-images.githubusercontent.com/4640763/104592423-1aba4500-5666-11eb-9417-a5e0814f9829.png)

Note the grey layer (RRB) does not start at x=0, the first column of pixels in the white layer(base) is completely unobstructed

**Comment by gardners** [comment]
I'll try to take a look.

**Comment by dansanderson** [comment]
This issue should be closed. It was decided to not correct the issue to preserve compatibility with existing software. See comment from @gardners here: https://github.com/MEGA65/mega65-core/pull/627

(I don't have perms in this repo so I can't close it myself. :) )

**Comment by lydon42** [comment]
@dansanderson @ki-bo on 13th dan writes we don't fix it, on 19th there is a commit from ki-bo adding a -1. Did we change our mind and fixed it anyways? I can't remember...

Please clarify by comment and close the issue afterwards!

**Comment by ki-bo** [comment]
Indeed, this was discussed again in Steerco and we decided to fix this one along with some other VIC bugs. It is already fixed in development for quite some time and did not seem to provide any issues so far.

**Comment by lydon42** [comment]
Yeah, and it's already in 0.96 release.
