### ISSUE TITLE
Allow masking of each pixel row to allow for more flexible RRB Y scrolling

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#340]
When using the RRB's ability to fine adjust char addresses to scroll in the Y direction, it means you can't easily scroll individual tiles vertically, because you need blank rows of char data above and below, which also basically means you can only vertically scroll tiles that are vertically laid out in a particular way.

To resolve this, I intend to implement a mechanism where the individual pixel rows of each char can be drawn or not drawn. This would allow masking the rows of char data that have come from the previous or next char tile, thus avoiding the need to have blank data there.

**Comment by geehaf** [comment]
Hi - a fix test is now available for this (https://github.com/MEGA65/mega65-tools/pull/122) but I'm not sure if we need to update the status/label from "fix test required"? Cheers.

**Comment by gardners** [comment]
test_340.c in mega65-tools has been updated and improved and confirms that this issue has been fixed.

**Comment by geehaf** [comment]
Hi Paul, Thanks for the update - it looks like you've been busy, extending
the range of tests and fixing the rowmask issue. On Australia day too. Nice
work.
Cheers,

George

**Comment by lydon42** [comment]
Running the test with a fixed core gives the same result as with a release core: a fail.

Looks to me like the wrong pixels are read? Or perhaps you don't set video mode correctly (my system defaults to NTSC)?

**Comment by lydon42** [comment]
Fixed and beautified test.
