### ISSUE TITLE
Using Extended Attributes Bold and Reverse to change palette banks produces corrupt result

### ISSUE THREAD

**Issue by M3wP** [MEGA65/mega65-core#342]
Using the ATTR flag of $D031 and the attributes flags BOLD and REVERSE of the colour ram bytes to change the palette used to the alt palette in $D070 does not work.

The result is a corrupt display with only part of the expected change on screen.

**Comment by gardners** [comment]
`src/tests/test_342.c` exists in the mega65-tools repo to test this, and confirms the problem is fixed.
