### ISSUE TITLE
Missing dependancy: exomizer

### ISSUE THREAD

**Issue by rdpeake** [MEGA65/mega65-core#347]
The build requires exomizer to create some of the embedded firmware files, however there is no mention or reference to this within build instructions or anywhere else in the repo

**Comment by M3wP** [comment]
ALSO!!

We need to include the package ImageMagick as a dependency as well as requiring an old version of libtinfo (version 5 in libtinfo5 package).

**Comment by gurcei** [comment]
Adding a cross-link to a similar ticket #363

**Comment by lydon42** [comment]
See #514
