### ISSUE TITLE
nexys4ddr target - obsolete or reinstatable?

### ISSUE THREAD

**Issue by Ben-401** [MEGA65/mega65-core#364]
I only have the nexys4ddr hardware (dont have the widget board).
Currently the 'nexys4ddr fails building due to #363 and other things.

Id like to get the nexys4 target building, but come someone please advise if this target hardware is incompatible and not worth the effort, or is there a possibility that the design could be migrated to fit and work to some level using:
- vga output,
- PS2/USB keyboard
- SDCARD
- etc.

**Comment by lydon42** [comment]
nexys4ddr-widget is the correct target for nexys4ddr and nexysA7.
