### ISSUE TITLE
HyperRAM read failure

### ISSUE THREAD

**Issue by steph72** [MEGA65/mega65-core#379]
On the R3 board, when 

1) writing to address A, 
2) reading from address A again, and then
3) repeatedly reading from address B 

sometimes the contents of address A is returned instead of the contents of address B. 

After writing a different value to address A, address B switches to the correct value.

Attached is a BASIC65 program that demonstrates the issue.

[hyperbug.zip](https://github.com/MEGA65/mega65-core/files/6411534/hyperbug.zip)

![E436731C-BCE5-4C82-A6AB-54EA5ED1BE12](https://user-images.githubusercontent.com/51749597/116816426-2ae92800-ab62-11eb-8454-69361861f607.jpeg)

**Comment by Edilbert** [comment]
I can confirm this issue.
The program runs with no errors on XEMU, but shows read failures on the MEGA65 dev kit.
When I inspect the attic RAM with the BS monitor after running the program, its shows correct values.
So it seems, that under certain conditions the read access does not return the value from the correct memory page.

**Comment by lydon42** [comment]
BASIC test is a little bit faulty, NEXT R is missing between 200 and 210.
Runs without fault. Fix already merged with master.

**Comment by lydon42** [comment]
Unittest for this is test_585
