### ISSUE TITLE
Internal flasher display problems

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-core#382]
Internal flashing has progress bar problems when flashing larger than 4mb bitstreams
![image](https://user-images.githubusercontent.com/3924427/117254378-9e33b800-ae48-11eb-8ad1-1781fbe7e793.jpeg)

**Comment by gardners** [comment]
Hmmm... There is an A100T #define that is supposed to adjust for this, but seemingly doesn't.
I am assuming that this was on a MEGA65 R3 board?

**Comment by gardners** [comment]
Ok, found the probable cause

**Comment by gurcei** [comment]
@deftmega Just to confirm, did this problem go away for you after Paul added his fix? If so, we can close the card.
