### ISSUE TITLE
Some USB / PS/2 Keyboards use different scancodes

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#384]
See discussion on Discord about this with @TheChief etc:

```
Cursor left: E0 6B, Cursor right: E0 74, Cursor up: E0 75, Cursor down: E0 72
See also here for reference: http://philipstorr.id.au/pcbook/book3/scancode.htm
```

etc

Problem seems to be some keyboards use extended scancodes for cursor keys, instead of non-extended ones.

**Comment by gurcei** [comment]
Oh, I saw @TheChief had some fixes merged in, so perhaps we can close this ticket now?

**Comment by lydon42** [comment]
Old, no confirmation or notice about still being a problem. Please reopen if this is still an issue.
