### ISSUE TITLE
Build.md does not specify needing to manually build GHDL

### ISSUE THREAD

**Issue by waym0002** [MEGA65/mega65-core#389]
To compile `simulate` it requires GHDL to be complied first, which in turn also needs gnat from apt.

Gnat should be added to the list of pre requisites and GHDL needs to be either added to the makefile for simulate or build.md should explain how to compile GHDL yourself.

**Comment by ande0207** [comment]
G'day @waym0002,

This is a very fair point I've also ran into - I've proposed a pull request to address this issue how I best see fit.

Cheers

**Comment by gurcei** [comment]
As @ande0207's PR has now been merged to development branch, I'll close this ticket.
