### ISSUE TITLE
Register bit to indicate if MEGA65 is on real hardware or emulated/simulated

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#393]
Gurce and LGB have requested a way to tell whether a MEGA65 is emulated/simulated or not.
The $D629 target ID byte can be set in Xemu to pretend to be any MEGA65 hardware type, so that can't be used.

Enabling $D60F bit 5 to provide this identification.

**Comment by gurcei** [comment]
Yep, this is sorted out now.
