### ISSUE TITLE
Pressing 0 to 9 to select alternate ROMs at boot doesn't work at the moment

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#395]
You are _supposed_ to be able to hold 0 through 9 down on the keyboard when resetting the MEGA65 to have it load an alternate ROM named MEGA65x.ROM, where x is the key held. e.g., holding 2 down on boot should load MEGA652.ROM

This feature also needs to be documented in the books.

**Comment by gurcei** [comment]
This works fine now.
