### ISSUE TITLE
Freezer erroneously activates vertical crosshair line

### ISSUE THREAD

**Issue by steph72** [MEGA65/mega65-core#400]
Sometimes, after accessing the freezer and returning, a vertical red line is overlaid on the screen (and stays there until reset).

![image0](https://user-images.githubusercontent.com/51749597/121917327-4afd3100-cd35-11eb-9ed1-ef6add842326.jpg)

**Comment by gardners** [comment]
I think I know the cause for this: Those registers read different values to what can be written to them.
They should be made to read the written values if read from hypervisor mode.

**Comment by gurcei** [comment]
I tried a recent bitstream, and it seemed to be this problem has gone away. Ok to close the ticket?

**Comment by gardners** [comment]
Yes, I believe I fixed it, so close the issue.
