### ISSUE TITLE
Feature Request - DMA Line fetch 

### ISSUE THREAD

**Issue by smnjameson** [MEGA65/mega65-core#401]
Having the ability to read from a texture source using the same line stepper used for DMA line drawing would enable many new powerful effects, including rotating textures.

Lets see this on Mega65....

![image](https://user-images.githubusercontent.com/4640763/121972154-4a36c000-cd72-11eb-9119-d8225999d76c.png)

Thank you :)

**Comment by lydon42** [comment]
@gardners this seems to be implemented, can we close?
