### ISSUE TITLE
make: ***No rule to make target 'ghdl/ghdl_mcode', needed by 'simulate'. stop

### ISSUE THREAD

**Issue by Drashti287** [MEGA65/mega65-core#405]
![image](https://user-images.githubusercontent.com/80866322/122354385-176a1300-cf90-11eb-9a8b-e588113f9a49.png)

**STEPS:**
1. goto ghdl directory
2. run `./configure`
3. run `make`
4. try again with `make simulate`

**Comment by gurcei** [comment]
I noticed there was a recent commit to 'development' branch relating to adding such a target:

https://github.com/MEGA65/mega65-core/commit/73a2cab629aabd9188f83d943ecdeb1ed30ee145

So if you're not presently working from the 'development' branch, I suggest switching to it and trying again from there and see how you go.

**Comment by gurcei** [comment]
Ok, as we haven't heard back anything on this ticket, and there are users that have successfully used "make simulate" on 'development' branch recently, I'll close this ticket.
