### ISSUE TITLE
Hyppo does not write enable image1

### ISSUE THREAD

**Issue by Edilbert** [MEGA65/mega65-core#407]
When mounting disk images for drive 0 and drive 1, drive 0 is write enabled, but drive 1 not.
The isssue is probably in "hyppo/dos.asm": line 918 which enables writing for image 0 only.
` 
 909 dos_d81write_en:

 910         lda $d68b
 911         and #$03
 912         cmp #$03
 913         bne td81we1
 914         ora #$04
 915         sta $d68b
 916 
 917         ;; Mark disk image write-enabled in proces descriptor
 918         lda currenttask_d81_image0_flags
 919         ora #d81_image_flag_write_en
 920 
 921         sec
 922         rts
`

**Comment by gardners** [comment]
Yes, this routine needs to not mess up the disk image 1 flags.
There should also be a version of the call for write-enabling disk image 1, without messing up disk image 0 flags.
