### ISSUE TITLE
Pixel poo appearing in bitplane mode(s) at bottom left and top left corners

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-core#415]
One pixel top left and a small row bottom left can be spotted, please check with attached disk image

![poopixels1](https://user-images.githubusercontent.com/3924427/123513364-2b4afe80-d68d-11eb-9d7d-9805365ded9f.png)

![poopixels2](https://user-images.githubusercontent.com/3924427/123513365-2d14c200-d68d-11eb-83c3-42f66350e163.png)

[MEGADEMO.zip](https://github.com/MEGA65/mega65-core/files/6720107/MEGADEMO.zip)

**Comment by deftmega** [comment]
Pixel poo is related to CRT emulation! No poo if CRT emulation is disabled. please fix crt emulation.

**Comment by lydon42** [comment]
Shorter test:
10 SCREEN 320,200,1
20 LINE 319,0,319,0:REM DIRT LOWER RIGHT
30 LINE 0,10,0,10:REM DIRT UPPER LEFT
40 GETKEY A$
50 IF A$="X" THEN GOTO 80
60 POKE $D054,PEEK($D054) XOR 32:REM TOGGLE CRT
70 GOTO 40
80 POKE $D054,PEEK($D054) AND 223:REM DISABLE CRT
90 SCREEN CLEAR
