### ISSUE TITLE
ROM related: Text mode effects are broken

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-core#416]
in current ROM (tested: 9200186.BIN), text mode effects are broken, no visible chars; please test with attached disk image

![texteffects](https://user-images.githubusercontent.com/3924427/123513418-6ea56d00-d68d-11eb-8f8c-afa078ad230c.png)

[MEGADEMO.zip](https://github.com/MEGA65/mega65-core/files/6720110/MEGADEMO.zip)

**Comment by Edilbert** [comment]
fixed with ROM version 920188
