### ISSUE TITLE
Interesting things going on with lines and possibly circles in BASIC

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-core#418]
please see attached images for reference, disk images also attached
![lines](https://user-images.githubusercontent.com/3924427/123513550-1a4ebd00-d68e-11eb-8437-4a1a004a45c6.png)
![lines2](https://user-images.githubusercontent.com/3924427/123513551-1b7fea00-d68e-11eb-932e-ae67877f2b4a.png)
![lines3](https://user-images.githubusercontent.com/3924427/123513552-1d49ad80-d68e-11eb-8641-892944bf8f0b.png)
[MEGADEMO.zip](https://github.com/MEGA65/mega65-core/files/6720119/MEGADEMO.zip)

**Comment by Edilbert** [comment]
I think, this effect is generated by selecting the "raster effect" on HDMI display.

**Comment by deftmega** [comment]
negative, I always watch on VGA while capturing (the above) on HDMI

**Comment by deftmega** [comment]
correction: you are of course right Edilbert for certain effects happening. But I was referring to double lines on left side (bottom screenshot), extra pixels on left side (top screenshot), and doubled lines on top (middle and bottom screenshot).

**Comment by Edilbert** [comment]
I see. That is probably related to the pixel poo issue.
It seems, that the scanline from memory, that is transferred to display, is not properly aligned.
There seems to be an offset of 1 pixel. This would explain effects on the left and the right border.

**Comment by deftmega** [comment]
Pixels appearing on left border is related to CRT emulation! also see issue #415. Please fix crt emulation.

!!!Only duplicated top vertical line remains as an issue if CRT emulation is turned off.!!!

**Comment by frehwagen** [comment]
Top issue is the same as in  #432
