### ISSUE TITLE
no-compile - cc65 dependancies

### ISSUE THREAD

**Issue by Ben-401** [MEGA65/mega65-core#42]
after the mega65-fdisk issue, i then get an error during compile of the fdisk programs.
To fix, you need to download "cc65", compile it, and place the binaries in "/usr/local/bin".

I suggest the documentation be updated to reflect this dependency.

I used:
```
$ cd .. (to get out of the $git_root dir)
$ git clone https://github.com/cc65/cc65.git
$ cd cc65
$ make
$ sudo cp bin/* /usr/local/bin
$ cd ..
$ cd mega65-core
```
and then the ```make``` continued to execute the XST commands.

**Comment by gardners** [comment]
By all means update the documentation for this, and also explaining the
work around for building the fdisk program.

Paul.

**Comment by gardners** [comment]
Has this documentation been fixed?

**Comment by Ben-401** [comment]
yes is documented now, at head of px100mhz
