### ISSUE TITLE
Implement hypervisor call to read a file direct into hyperram / Attic RAM

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#439]
Current load file hyper call (00:36) can only read into bottom 16MB, which means we can't load into attic RAM.
Implement 00:3E to do the same, but load into 16MB HyperRAM / Attic RAM region.

**Comment by gardners** [comment]
Can be closed when confirmed working.

**Comment by lydon42** [comment]
As the new flasher first loads the COR into hyperram, this function works as intended.
