### ISSUE TITLE
Use Dip switch to select default boot slot

### ISSUE THREAD

**Issue by adtbm** [MEGA65/mega65-core#443]
Suggestion:
It would be good, if the user could use two Dipswitches to select the Default boot slot, the MEGA65 should boot from.

**Comment by gardners** [comment]
This will need to be dipswitch #4, because #1-#3 are already used. i.e., allow selecting between only two different bitstreams.

**Comment by lydon42** [comment]
Tested with recent development core in slot 0: works as expected.
