### ISSUE TITLE
Exit and reboot to onboarding - reboots to Open Rom.

### ISSUE THREAD

**Issue by mindrail** [MEGA65/mega65-core#460]
When in the configuration menu and doing an exit and reboot to on-boarding.. It reboots to open rom.
If you power off and back on it then enters the on-boarding.

**Comment by lydon42** [comment]
Is this still happening? Which core release are you using?

**Comment by lydon42** [comment]
I tested this in the last week quite often on both r3 and r3a: this is fixed.
