### ISSUE TITLE
Colour registers should read $Fx in VIC-II IO context

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#462]
This causes problems with, for example, STRAIGHT-UP (https://straightup.drwuro.com/) (even if due to a bug in that game meaning it reads $D021 when it meant to read $D012, it still acts as a test for this).

**Comment by lydon42** [comment]
This looks solved to me, and it is already merged into master. PEEK in C64 mode has high bits set, I see no problem with the game.
