### ISSUE TITLE
($nn,SP),Y is broken

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#497]
It adds the BP register to the _address on the stack that is being referenced_, which really borks things up when BP != 0.

This breaks Jim Nicholl's nice code that uses this opcode to fix another bug in the MEGA65 hypervisor.

**Comment by lydon42** [comment]
Todo: unittest

**Comment by lydon42** [comment]
At least the opcode fix should be ported to the development branch. I will do that in the next days, together with the unittest for verification.

**Comment by lydon42** [comment]
Unit test added to mega65-tools.
Checks ok with latest development.
