### ISSUE TITLE
Update FDISK for filesystem pre-population

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#510]
FDISK now supports pre-populating SD CARD contents from files embedded in flash core slot 0 after the bitstream.

For bonus points, load BANNER.M65 from flash instead of SD card for faster banner display and boot.

**Comment by lydon42** [comment]
Tagging commits for release-build tools:
mega65-core: 6830206, fc504ef, 1d72dbc, 4b8c33e
mega65-tools: [6c64a94](https://github.com/MEGA65/mega65-tools/commit/6c64a941f3dd5d0afcaa7b64dc6c92563d09179f#diff-7addeaef2d517629b18ccd3777ecfab2f0bb5dce809f47a5db65d1e1849570ba), [794f851](https://github.com/MEGA65/mega65-tools/commit/794f8516f6bd5ad2dc5047713f656aa0fae40867#diff-7addeaef2d517629b18ccd3777ecfab2f0bb5dce809f47a5db65d1e1849570ba), [e54d90e](https://github.com/MEGA65/mega65-tools/commit/e54d90e73ace2475eb8fa5d7cfe6022053e0d103#diff-7addeaef2d517629b18ccd3777ecfab2f0bb5dce809f47a5db65d1e1849570ba), [2f49040](https://github.com/MEGA65/mega65-tools/commit/2f490401b54d966f0dfac45434e930bac630a932#diff-7addeaef2d517629b18ccd3777ecfab2f0bb5dce809f47a5db65d1e1849570ba)
mega65-release-prep: [70d9a38](https://github.com/MEGA65/mega65-release-prep/commit/70d9a3893607093d1aef5ef73306345d7870d67a#diff-aca933b18c0afaf00d66cdb4d3b606b99cad6f52a41654b5fe9c4d86e50e439d), [ca1cf11](https://github.com/MEGA65/mega65-release-prep/commit/ca1cf111186cd9dfb2785f4646fb04f539d0a066#diff-aca933b18c0afaf00d66cdb4d3b606b99cad6f52a41654b5fe9c4d86e50e439d)
