### ISSUE TITLE
Make drive noise for SD-card access configurable.

### ISSUE THREAD

**Issue by Edilbert** [MEGA65/mega65-core#518]
It would be nice to make the drive noise configurable.
Some users prefer to hear the drive noise only, when the internal drive is accessed.

Also different LED colours for access to SD-card image or internal drive would be great.

**Comment by lydon42** [comment]
This needs to be checked if it is really working... it come up a few days ago and I was not able to get the sound disabled via a poke.
This is also missing from configuration menu.

**Comment by lydon42** [comment]
Closing the old one as duplicate, keeping the new ones.
