### ISSUE TITLE
FREEZER "reset" causes damage to machine state, requiring power cycle to restore

### ISSUE THREAD

**Issue by M3wP** [MEGA65/mega65-core#530]
When the "reset" function of the FREEZER is used, the machine state becomes damaged, requiring a cold boot to restore.  This can be confirmed with a warm boot and monitoring the boot report for the warning "hicked hypervisor".

Many things will no longer work as expected and especially, using the FREEZER again will mostly likely hang the machine.

There is a related issue:  #499

**Comment by lydon42** [comment]
"hicked hypervisor" means that this no cold boot and so HICKUP.M65 is not loaded.

But yes, some stuff stays on a warm boot that better should be reseted... for example the vic-regs that caused #499

**Comment by lydon42** [comment]
is this fixed? does someone has a test for this?
