### ISSUE TITLE
Setting the date when onboarding ends up inconsistent with date in BASIC

### ISSUE THREAD

**Issue by mindrail** [MEGA65/mega65-core#540]
Setting the date in onboarding makes the date one day too far ahead when booted and displaying date in basic.

Note. If you then CONFIGURE the MEGA65 and set the date that way, it retains the correct date and stays consistent.

Using ROM V920349

**Comment by lydon42** [comment]
The +/-1 is actually in mega65-libc time.c getrtc/setrtc. This is used by onboard.c

mega65_config.s and probably the closed ROM do it in asm...

Now the question is: which is correct?

**Comment by lydon42** [comment]
fixed in mega65-libc and updated with commit 82723e7dc48c7c7c0a0074053f7acf5c49ed789f
