### ISSUE TITLE
Freezing with RESTORE while inside of FREEZER should be suppressed

### ISSUE THREAD

**Issue by lydon42** [MEGA65/mega65-core#548]
Currently you can freeze inside the freezer, which is not really helpful. This should be suppressed.

This might be a mega65-freezemenu issue... not sure.

Reported here: https://www.forum64.de/index.php?thread/126205-bug-report-freezer-when-freezing-during-freeze-there-is-no-way-out-anymore/

**Comment by gurcei** [comment]
I recently tested this on build 201, and can confirm that this works, can no longer freezer the freezer. Will close this one off, thx @gardners :)

**Comment by MauriceMEGA65** [comment]
Great, thank you!
