### ISSUE TITLE
Get rid of the C64 Mode

### ISSUE THREAD

**Issue by oe3gwu** [MEGA65/mega65-core#559]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would love to boot C64 applications direct from MEGA65 mode. This is way faster in loading programs, and openROM's will support this too, so it should be able to port this to the MEGA65 ROM's. OpenROM's are years from completion.

**Describe alternatives you've considered**
none

**Comment by lydon42** [comment]
We won't get rid of the C64 mode. The C64 mode of the MEGA65 will probably never be a very compatible C64 because of the different CPU (well not as compatible as the C128 C64 mode was anyways).
The C64 core is in development and that will be most compatible in the end.
