### ISSUE TITLE
D81 image creator adds ".D81" to the disk name

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-core#575]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65
 - Core Commit: 899cf4f
 - ROM Release: 920365

I have SD card contents updated to the same build as the core.

**Describe the bug**
Freezer D81 disk image creator uses the name that you enter as both the .D81 filename and the CBDOS disk name, but it adds ".D81" to the disk name.

**To Reproduce**
1. Open the Freezer, then drive 0.
2. Select "NEW D81 DD IMAGE".
3. Enter the name "TEST", press Return. It creates the disk image.
4. Reset to BASIC with the new disk image mounted in drive 0 unit 8.
5. DIR

**Expected behavior**
The directory listing should show a disk with the name "TEST", but it shows the disk name as "TEST.D81".

**Additional context**
HEADER "TEST" on the newly created image will correct the name, so it's an easy workaround. I'm guessing it's also an easy fix in makedisk.c.

**Comment by gurcei** [comment]
We've merged @TheChief 's fix in, so will close this one
