### ISSUE TITLE
Floppy not recognised when going from GO64 to MEGA65 mode

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-core#599]
**Test Environment (required)**
See screenshot MEGA65 info, core 3253c5d

**Describe the bug**
While in GO64 mode, I used Freezer to mount my real floppy.
After mounting, I could write and read to/from floppy, so in G64 mode all was fine.

Then I went to MEGA65 mode via SYS58552.
After that point, the floppy was no longer recognised, and DIR give me a READ ERROR.

I tried:
1. Mount the floppy again via Freezer --> same read error after DIR 
2. Mount the floppy in BASIC via MOUNT --> same read error after DIR 
3. Eject the disk, reinsert the disk, MOUNT --> success

**Expected behavior**
MOUNT of a floppy disk should work after switching between MEGA65 and GO64 mode without re-inserting the disk.

**Screenshots**
![5C4F9A7F-D8FF-4CEF-B274-6F2D03852A0A](https://user-images.githubusercontent.com/75681098/183310680-2617313b-b4b4-4e09-8940-6a01c978caf1.jpeg)

![9FD167CA-CA57-4922-8427-6CE92A53155C](https://user-images.githubusercontent.com/75681098/183310776-20fa698d-3711-4157-a8d7-f3885d3e2eb4.jpeg)

![7EBA7741-D57C-4E68-BA30-D254C5467C38](https://user-images.githubusercontent.com/75681098/183310684-4b0fed55-fa3b-41a2-aae7-761302634503.jpeg)

**Comment by lydon42** [comment]
Can't confirm this on RC1, just did it with the hybernated disk and after the SYS to MEGA65, autoboot kicked in and started the game, as it is expected.
