### ISSUE TITLE
RC 0.95: Onboarding date setting shows day -1

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-core#614]
**Test Environment (required)**
* Platform: MEGA65
* Core Commit: https://github.com/MEGA65/mega65-core/commit/dadad1c885c95d61f49387648551e6448586d077
* ROM Release: 920376

**Describe the bug**
It appears the Onboarding date setting interface reads the date from the RTC with the day value -1. After setting it, it appears in BASIC as the set day value +1. This is true even when setting the day value to 31: BASIC shows a day of "32."

*Important:* I am running a Grove external RTC. My batch-1 MEGA65 has a non-functional internal RTC (no ticks).

This may or may not be related to https://github.com/MEGA65/mega65-core/issues/613.

**To Reproduce**
1. Power off, hold Alt, power on. Select Configuration (1).
2. Chipset tab, notice the current date setting. (Right now, mine says 15-SEP-2022.)
3. Done tab, Exit and Reboot to Onboarding.
4. Notice that Onboarding things the day value is -1. Mine says 14/Sep/2022.
5. Use F9 and F11 to set the date to 31/Oct/2022. Press Return to save and exit.
6. BASIC header displays `32-OCT-2022`, as does `?DT$`.

**Expected behavior**
Onboarding should show the current set date accurately, and should set it accurately.

**Additional context**
The time and date set in Onboarding appears in BASIC, but is reverted when I power off and on again. This might be a separate issue, and may be specific to Grove external RTC support.

**Comment by lydon42** [comment]
duplicate #540
