### ISSUE TITLE
https references to submodules

### ISSUE THREAD

**Issue by frehwagen** [MEGA65/mega65-core#62]
Please use https referencing to github submodules:

 [submodule "src/mega65-fdisk"]
 	path = src/mega65-fdisk
 	url = https://github.com/MEGA65/mega65-fdisk.git
+[submodule "cc65"]
+	path = cc65
+	url = git@github.com:cc65/cc65.git

**Comment by gardners** [comment]
Hello,

hmm. We had a weird problem where it refused to push them earlier today,
which is why we went back to the git urls, but we can try again.

Paul.

**Comment by gardners** [comment]
Fixed in 221b2d3
