### ISSUE TITLE
sdcardio: D6A1.3 SDFDC:SILENT seems to have no effect

### ISSUE THREAD

**Issue by lydon42** [MEGA65/mega65-core#621]
Title says it all.

There is some mysterious logic and D6A0 motor settings seem not to honor this flag.

**Comment by lydon42** [comment]
D6A0 seems not to be a problem, adding a check for silent_sdcard there does not change anything.

**Comment by lydon42** [comment]
#518

**Comment by lydon42** [comment]
Use `SETBIT $D6A1,3` to enable.

**Comment by ki-bo** [comment]
As this one is now merged to development, we can probably close it

**Comment by dansanderson** [comment]
I can confirm that the latest development core supports both $D6A1.3 and setting the disk noise option in Configuration on an R5 board. Assuming this works similarly on an R3 board, this can be closed.
