### ISSUE TITLE
MEGA hangs in Hypervisor after configure

### ISSUE THREAD

**Issue by bubbob42** [MEGA65/mega65-core#632]
**Test Environment (required)**
 - Platform: DevKit, MEGA65
 - Core Commit:  93d55f08
 - ROM Release:  920377

**Describe the bug**
After entering Mega65 configuration and leaving with "save as defaults and exit", Mega65 will hang in Hypervisior screen. A reset is required to reach BASIC.

**To Reproduce**
1. Enter config menu (hold alt and switch machine on)
2. leave via "save and exit"

**Comment by lydon42** [comment]
This was fixed by 0.96 by prompting the user to power-cycle the system.
