### ISSUE TITLE
HYPPO should restore ROM area, even if marked write-protected

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#634]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: ALL
 - Core Commit: ALL
 - ROM Release: N/A

**Describe the bug**
Modifying ROM memory from the freezer has no effect if ROM write-protect is enabled. The root cause is the unfreeze routines don't un-protect the ROM before unfreezing.

**To Reproduce**
1. Freeze
2. Modify some string in the ROM, e.g., the C64 mode basic banner around $2E400
3. Exit freezer
4. GO 64 or SYS64738 to restart C64 mode (don't use reset button, as that will reload ROM)
5. Observe that your changes did not survive unfreezing

**Expected behavior**
The changes made to ROM banks should be effective after unfreezing

**Screenshots**
N/A

**Additional context**
This is why loading ROMs in the freezer never worked.

**Comment by gardners** [comment]
believed fixed, but requires confirmation.

**Comment by lydon42** [comment]
ROMLOAD does work with this fix.

**Comment by lydon42** [comment]
This seems to be broken again in latest development.

**Comment by lydon42** [comment]
Question for @gardners: is it really possible to write a m65 tool unit test for this, so this can be regression tested? The unit test would need to get the system into hyppo mode and then try to write ROM space... (because of the fix-test-required label).
