### ISSUE TITLE
Ethernet controller sometimes still writes to buffer held by the CPU

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#636]
**Test Environment (required)**
All versions. Easiest to reproduce using etherload on Nexys or other A100T target due to lower number of eth RX buffers

**Describe the bug**
Eth controller can overwrite the eth RX buffer held by the CPU.

**To Reproduce**
1. Build etherload to disable whole of ACK checking.
2. Load a program, and note that it is often corrupted.

**Expected behavior**
No corruption occurs

**Screenshots**
<Hand drawn diagram of a snail with a TV on its back for entertainment purposes only>

**Additional context**
None

**Comment by ki-bo** [comment]
The fix for this was committed in https://github.com/MEGA65/mega65-core/commit/74d636b1766dcab1923af439b9fd6d7247ae58c9
