### ISSUE TITLE
Alternate ROMs in Slot 9 (MEGA659.ROM) cannot be selected when powering M65 with Numeric 9 Pressed

### ISSUE THREAD

**Issue by michaelniotis** [MEGA65/mega65-core#664]
**Test Environment (required)**
Stock ROM V920377

**Describe the bug**
Selecting Slot 9 for Powering Up M65 ignored 

**To Reproduce**
1. Add ROM at slot 9 (MEGA659.ROM file in SD Card)
2. Press "9" while Powering the M65
3. System Boots to Default ignoring Slot 9 

**Expected behavior**
Being able to use ROMs in SLOT 9

**Comment by deftmega** [comment]
In https://github.com/MEGA65/mega65-core/blob/master/src/hyppo/main.asm please change 

@checkkey:
        cmp #$30
        bcc kr2
        cmp #$39
        bcc kr1

to

@checkkey:
        cmp #$30
        bcc kr2
        cmp #$3a
        bcc kr1

that should solve it.

kthxnbye

**Comment by lydon42** [comment]
Fixed by @gurcei in e296c3c992c1d9db678e7d6876f11a7f633ff7b3
