### ISSUE TITLE
Can Softlock the MEGA65

### ISSUE THREAD

**Issue by Spidamouse** [MEGA65/mega65-core#67]
While in matrix mode, if you stop the CPU, trigger the leave matrix mode hypervisor trap and then single step through until you leave matrix mode, you can no longer resume the CPU without a serial input.

This is because the CPU is paused and thus the hypervisor can no longer trigger matrix mode.
The user can not resume the CPU from user mode.

**Comment by lydon42** [comment]
Closing as this is very old. If this still happen on latest cores, please open a new issue.

**Comment by gardners** [comment]
I believe it still happens, but happy to have closed for now as "won't fixed", as its quite an uncommon combination.
