### ISSUE TITLE
Allow double vertical resolution chars in V200 mode

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#678]
**Is your feature request related to a problem? Please describe.**
Even in V200 mode we use 8x8 chars, like the C65 did. It would be nice to be able to do VGA-style increased resolution chars at 40x25 / 80x25 modes.

**Describe the solution you'd like**
It would be nice to have the _option_ to use 16px tall chars, that are drawn using V400, so that they are the same size as normal, but with increased vertical resolution.

**Describe alternatives you've considered**
Live with the status quo and/or hide under a rock (after first checking for snakes and spiders, since I do live in Australia, after all)

**Additional context**
N/A

**Comment by lydon42** [comment]
Paul tells me this is good and done!
