### ISSUE TITLE
Weird color line fragments in 640x400 16 color graphic mode

### ISSUE THREAD

**Issue by sir-lazarus** [MEGA65/mega65-core#701]
Tested on a real Mega65 with ROM 920377 and ROM 920383 in PAL Mode Batch 2 Release Core

When I draw text or lines in a Basic program with Basic commands like the following:

10 SCREEN 640,400,4
20 FOR C=1 TO 16
30 PEN C-1 : CHAR 10, C*8,1,1,2,"THIS IS A TEXT EXAMPLE" : NEXT C
40 BOX 0,0,200,150
50 GETKEY a$
60 SCREEN CLOSE

I got weird color fragments at the text and lines.
The same code and rom on the Mega65 Emulator works fine with no issue.
So I assume a core problem.

**Comment by lydon42** [comment]
Duplicate to #689
