### ISSUE TITLE
Keyboard scanning at 40MHz sometimes has problems

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#71]
It seems to change between bitstream builds, suggesting something subtle is going on, but keyboard scanning at 40MHz is sometimes quite broken.

Probably best to write a matrix scanning tester to try to figure out exactly what is going on.

io_settle_delay in gs4502 should be freezing the CPU for more than long enough for the keyboard matrix to stabilise.

**Comment by frehwagen** [comment]
Duplicate of #115
