### ISSUE TITLE
MEGA65R4 core 3.5mm audio output stops and requires a power-off for 15 seconds to recover

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#721]
**Test Environment (required)**
MEGA65 R4

**Describe the bug**
Audio stops working on 3.5mm jack after some unknown time or situation.

**To Reproduce**
Leave MEGA65 R4 on for some time. Try to use 3.5mm audio, repeat until it doesn't work any more.

**Expected behavior**
Audio should be present, but isn't

**Screenshots**
[funnycat.gif not found]

**Additional context**
PGS has confirmed the bug, and will investigate it by adding access to ADC I2C registers. Probably something sets or something, and needs reseting.

**Comment by ki-bo** [comment]
This one was reported to be fixed according to @gardners , closing
