### ISSUE TITLE
Stuck in Onboarding after going there from Configuration

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-core#722]
**Test Environment (required)**
- Platform: MEGA65
- Slot 0: 683-cartflash,20230612.07,cae3b0b
- Slot 1: development,20230816.13,ea3508e

**Describe the bug**
I got stuck in Onboarding after going there from Configuration via "Exit and reboot to onboarding." Leaving Onboarding, pressing the reset button, and powering off and on all returned to Onboarding. I can enter the utility (Alt) and core (No Scroll) menus in this state.

I was able to remove the external microSD card, copy off data to a PC, then reformat the microSD card in the MEGA65 SD card utility. For SD card files, I selected the development core in slot 1. After reinstalling the ROM file and rebooting, it entered Onboarding one more time, then I was able to save and exit without issue.

I could then reproduce the issue by going back to Configuration, "Exit and reboot to onboarding." I would have called it a fluke except that I can reproduce it.

**Comment by lydon42** [comment]
Fixed by not resetting at the end, but asking the user to power cycle.
This also avoids booting into the slot 0 core by accident.
