### ISSUE TITLE
when leaving freeze menu SID stops

### ISSUE THREAD

**Issue by adtbm** [MEGA65/mega65-core#73]
i have experienced now several times, that, when leaving the Freezemenu by pressing "F3"
for certain programs the SID is not working anymore.
The rest of the game works, but no more audio output.

my setup:
Nexys4DDR with widgetboard.
Video: PAL

tested on:
International Soccer
Last Ninja 1
Spy vs Spy 1

**Comment by gardners** [comment]
This is almost certainly because we set $D418 to $00 when entering the freeze menu, and don't set it to $0F on exit.  This needs to be done in the hypervisor unfreeze code. Shouldn't be hard.

PS: Thanks for the detailed and actionable issue :)
