### ISSUE TITLE
Typing event queue: repeat is triggering too early?

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-core#738]
**Test Environment (required)**
You can use [MEGA65INFO](https://files.mega65.org?id=3eeb7d82-8bd7-44b7-82b6-cef29d123b0e) to retrieve this.
 - Platform: MEGA65
 - Core Commit: dea350f
 - ROM Release: 920387

**Describe the bug**
I'm occasionally seeing multiple strikes of a key press using the new keyboard scanner based on the typing event queue. At first I thought maybe our debounce timing needed tweaking, but as I experimented more I realized that when it happened, it appeared to have the frequency of the hardware-based key repeat logic, as if the key was in "repeat" mode on first press. I wonder if the repeat delay isn't getting reset correctly under certain circumstances, and enables repeat mode even when I have moved on to the next key.

**Comment by gardners** [comment]
That sounds like a plausbile explanation. Alternatively, it could be that the initial delay is not being reset, and it is using whatever fraction of it remains until the next timeout of it, or alternatively that it is using the repeat interval instead.
