### ISSUE TITLE
When mounting "BAD APPLE" demo disk with freezer, the sound is degraded

### ISSUE THREAD

**Issue by paich64** [MEGA65/mega65-core#741]
**Test Environment (required)**

 - Platform: MEGA65
 - Core Commit: Batch 2 factory core
 - ROM Release: 920377

**Describe the bug**
To run the demo you need to 
1) put the 3 files at the root of the SD card.
2) mount megapple.d81
3) load and run the .prg file

If 2) is done using the freezer, then the demo sound is broken 

if 2) is done from BASIC, then the sound is correct

"from BASIC" means :
DIR U12
MOUNT"MEGAPPLE.D81"

**To Reproduce**
1. Download attached zip file
2. extract and put the files at the root of the sd card 
3. mount the .d81 with the freezer
4. load and run the demo
[MEGAppleFiles.zip](https://github.com/MEGA65/mega65-core/files/12827364/MEGAppleFiles.zip)

**Expected behavior**
The sound should not be broken when mounting the .d81 file using the freezer

**Comment by lydon42** [comment]
Checked with latest MEGApple and development core, can't reproduce.

Note: there was also a newer version of the demo that fixed sound problems, as far as I can remember. But the demo was removed from filehost, so I can't tell anymore.
