### ISSUE TITLE
CONFIG: boot to default core after exiting config

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-core#752]
**Is your feature request related to a problem? Please describe.**
When I cold boot to the Configuration utility (hold Alt while switching on power), it boots with core slot 0 and loads Configuration from there. When I exit the Configuration utility, it proceeds to complete the boot sequence with core slot 0. This is counter-intuitive for people who normally keep a newer MEGA65 core in slot 1 (i.e. the default boot slot).

**Describe the solution you'd like**
The Configuration utility should start the boot process from the very beginning when exiting, including core slot selection. This better meets user expectations, and doesn't require communicating any additional information to the user.

**Describe alternatives you've considered**

1. Prefer loading the Configuration utility from the default boot core slot if appropriately populated, such that when exiting Config it proceeds to boot with the same core that loaded Config. Booting into a potentially newer (and core-matched) version of Config by default might be a useful bonus. (IIRC you can force loading Config from a specific slot by by starting the core from the core selection menu then holding Alt, which would be a way to force loading Config from slot 0 if needed.)
2. Have Configuration (from slot 0) detect whether there is a MEGA65 core in slot 1 or 2, and communicate this fact during exit. For example, it could be a message on the exit screen ("Save settings and boot to core slot 0"), a prompt that offers to reboot into the core selection screen, or just always boot into the core selection screen when this state is detected. (I would not have Config *always* exit to core selection: that'd be confusing in the common case of a machine with only slot 0 populated.)
3. Make this a feature of the Alt utility menu ("4: Boot with the default core"), and have Config exit to this menu instead of continuing the boot sequence. (Not my favorite option just because the Alt menu looks a bit tech-y right now, but it's a relatively intuitive UI flow: you started Config from Alt menu, so Config returns to the Alt menu.)
4. No code changes. Document this behavior in descriptions of using core slot 1 (and maybe add an advisory to the Config documentation in the User's Guide), as required knowledge for people installing alternate MEGA65 cores.

**Additional considerations**

I know we're working on making upgrading slot 0 safer for people without JTAG adapters. Maybe at some point, the recommendation would be for most users to keep slot 0 up to date with the latest stable core. Installing a core in slot 1 would be a less common case (e.g. people running dev cores as daily drivers), and better justifies expecting the user to learn about advanced behaviors of the Alt menu utilities.

**Comment by lydon42** [comment]
Booting to default core after config or onboard is to complicated to be implemented in all the utilities.

The easier solution is to ask the user to power cycle the system instead. This solution was implemented for the batch 3 release into config and onboard.

Please check.
