### ISSUE TITLE
RRB Reverse Y-row adjust

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#796]
See the attached documents from @RetroCogs explaining the desired feature and justification

[RRB_Sprites.pdf](https://github.com/MEGA65/mega65-core/files/14730038/RRB_Sprites.pdf)
[RRB_Vertical_scroll.pdf](https://github.com/MEGA65/mega65-core/files/14730039/RRB_Vertical_scroll.pdf)

**Comment by RetroCogs** [comment]
I've update the documents with the correct mask values and mask description
[RRB Sprites.pdf](https://github.com/MEGA65/mega65-core/files/14753762/RRB.Sprites.pdf)
[RRB Vertical scroll.pdf](https://github.com/MEGA65/mega65-core/files/14753763/RRB.Vertical.scroll.pdf)

**Comment by lydon42** [comment]
Extra issue for unittest added.
