### ISSUE TITLE
'reset' command for serial monitor

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-core#8]
It's not something urgent, but just a nice perk to have while debugging.

It'd be nice to be able to type a simple 'reset' command to the monitor and let the hardware reset (and save me from having to swap to the other keyboard and hold restore for a few seconds ;)).

Handy for when debugging startup issues where you want to study/debug and reset over and over again.

**Comment by gardners** [comment]
I have started implementing this.

On Wed, Aug 10, 2016 at 11:24 PM, Gurce Isikyildiz <notifications@github.com

**Comment by gardners** [comment]
This is fixed in 075cdb09317f87d96ca90578ee872f34b109608f, which will soon be merged onto development.

**Comment by gardners** [comment]
The command to reset is: !
It works by holding the reset line down for 15 clock cycles.
