### ISSUE TITLE
No vfpgatest.prg in master branch

### ISSUE THREAD

**Issue by holr0005** [MEGA65/mega65-core#80]
error code:
Making: src/utilities/vfpgatest.prg
Ophis/bin/ophis -4 src/utilities/vfpgatest.a65 -l src/utilities/vfpgatest.list -m src/utilities/vfpgatest.map -o src/utilities/vfpgatest.prg
src/utilities/vfpgatest.a65:417: Could not read ../../assets/vfpga-bitstream.bin
1 error
Makefile:419: recipe for target 'src/utilities/vfpgatest.prg' failed
make: *** [src/utilities/vfpgatest.prg] Error 1

The file is in the development branch but not master.

**Comment by gardners** [comment]
Thanks. I'll update the master branch to follow the development branch shortly.

**Comment by DoneRaging** [comment]
I'm no longer having this issue

**Comment by gardners** [comment]
Super. Will close the issue.
