### ISSUE TITLE
Doc string: CHXSGN is described inverted

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-core#807]
The Audio DMA signal CHXSGN (CH0SGN, etc.) has a doc string of "Enable Audio DMA channel X signed samples." This is inverted: the value of this signal is 0=signed, 1=unsigned.

Suggested new text: "Audio DMA channel X sample sign: 0=signed, 1=unsigned"

Previously: https://github.com/MEGA65/mega65-user-guide/issues/278

**Comment by lydon42** [comment]
Also changed CHXSGN to CHXUSGN to reflect the "set" state.
