### ISSUE TITLE
TI variable gets cleared after using RUN <line_number> command

### ISSUE THREAD

**Issue by pstankiewicz** [MEGA65/mega65-core#841]
**Test Environment (required)**
 - Platform: MEGA65R6
 - Core Commit: 3c10488
 - ROM Release: 920395

**Describe the bug**
`TI` special variable is cleared after using `RUN <line_number>` command

**To Reproduce**
1. Write simple BASIC program:
```
10 ? TI
20 FOR I = 0 TO 1000: NEXT I
20 ? TI
```
2. Run it normally using `RUN` for a couple of times, it should print growing number of seconds (correct behavior)
3. Run it using `RUN 10` command. It always prints:
```
   4.4768486E-5
   0.039128674
```

**Expected behavior**
No matter if using `RUN` or `RUN <line_number>` `TI` variable should not be cleared

**Comment by lydon42** [comment]
not a core issue, try mega65-rom-public.
