### ISSUE TITLE
Cant compile from make file - make file is a issue

### ISSUE THREAD

**Issue by piek0012** [MEGA65/mega65-core#89]
When trying to compile:
make: *** No rule to make target `src/tools/mega65-fdisk/m65disk.prg', needed by `bin/COLOURRAM.BIN'.

**Comment by piek0012** [comment]
I think the make file is a issue lol

**Comment by piek0012** [comment]
Comrades cant fix the crap either lol

**Comment by piek0012** [comment]
fixing the missing packages is already enough for me

**Comment by vvrbanc** [comment]
Hi, are you using the "development" branch? If so, what error are you getting?

**Comment by piek0012** [comment]
Sorry for the late response, I believe I am using the development branch. After installing the missing packages, I am getting errors from the makefile, I did modify some parts before. I'm not sure if im progessing or have made things worse.

My errors are: 

Makefile:559: warning: overriding commands for target `bin/COLOURRAM.BIN'
Makefile:553: warning: ignoring old commands for target `bin/COLOURRAM.BIN'
Makefile:629: warning: overriding commands for target `src/tools/monitor_load'
Makefile:611: warning: ignoring old commands for target `src/tools/monitor_load'
make: *** No rule to make target `src/tools/mega65-fdisk/m65disk.prg', needed by `bin/COLOURRAM.BIN'. Stop

**Comment by piek0012** [comment]
The solution was to declare the integer outside the function in the make files for fdisk.

**Comment by gardners** [comment]
Please indicate the specific change that is required, preferably with a pull request.

**Comment by rdpeake** [comment]
Currently building without issues, reopen if this still persists, or start new issue if there are new issues.
