### ISSUE TITLE
1351 emulation via serial monitor interface

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-core#9]
Add "m" command to serial monitor to allow setting mouse position and button status, and enable/disable this mouse emulation mode.

**Comment by gurcei** [comment]
Oh, I recall that 'm' was a pre-existing memory dump at present (28-bit addressing).

Or perhaps is there some re-arrangement of these command letters in Tim's re-working of the serial monitor interface?

**Comment by gardners** [comment]
Hello,

You're right. m/M is already taken. We can pick a different letter for the
mouse emulation.

Paul.

**Comment by lydon42** [comment]
Is serial monitor mouse emulation still a thing?
