### ISSUE TITLE
Proposal to remove SDHC bit from SD-flags (and the two commands), and maybe reuse this bit

### ISSUE THREAD

**Issue by lgblgblgb** [MEGA65/mega65-core#98]
It seems M65 does not support non-SDHC card anymore. So for clearness, I think, SDHC flag from SD flags should be removed altogether with the two commands meant for set/clear SDHC mode.

Also, I have the little idea, to reuse that bit for signalling multi I/O command(s) on the run, currently for the three multi-write commands, and hopefully in the future :) three other new commands for multi-read as well.

All of this to work, one should check if any M65 software (including hyppo/HDOS/fdisk) is OK with the change and does not expect the old SDHC flag to be set. I have the experience during Xemu development, that for example FDISK does not behave nicely eg when external SD bus is used, maybe the same applies if it does not see the SDHC flag to be set. On checking SD flags, it must be taken care, to mask out bits and check only those which are interesting for it, since it can break again and again in the future as well, if there is anything changed.

Well, hopefully I could manage to express myself well enough with my suboptimal English style ;)

**Comment by lydon42** [comment]
As @lgblgblgb is saying himself: 2019 this would have been an easy change, now it's a bit that mightbe used by a unknown number of programs.

This is outdated, so we close it. It might come up if one of the newer sdcard/fat issues and could then be handled there.
